### ISSUE TITLE
Adding/Removing Multiple Class Names

### ISSUE THREAD

**Issue by kerns** [bigskysoftware/_hyperscript#10]
Would be nice if something like `on click remove .hidden and .inline-block` or `on click remove .hidden .inline-block`was possible.

**Comment by ajusa** [comment]
Just tested this myself, and it works fine now. `on click remove hidden .inline-block` for example (or add) both work just fine. @1cg can this be closed?

**Comment by 1cg** [comment]
would like a test if one doesn't exist

**Comment by 1cg** [comment]
looks like I have one (and I implemented the feature :expressionless: ) I'll close.
