### ISSUE TITLE
Event name with `-`

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/_hyperscript#100]
I had to change my event name when I failed to use `cart-updated` or `"cart-updated"` in a piece of `hyperscript` code.

**Comment by benpate** [comment]
Yes.  `on my-event log it` throws a parse error.  It seems like dashes are used by other packages to generate event names, so this is something we should probably support.

**Comment by dz4k** [comment]
In hyperscript 0.8, you can now do this by quoting the event name:

```hyperscript
on "my-event" log it
on "cart-updated"(cart)
  -- do stuff with the cart...
```

**Comment by BoPeng** [comment]
Thanks, "as" reads better though

on "cart-update" as cart do
