### ISSUE TITLE
Problem with version 0.0.9 and tell command

### ISSUE THREAD

**Issue by gmzu** [bigskysoftware/_hyperscript#114]
This code working with version 0.0.7 no longer works when upgrading to version 0.0.9

``` html
<button class="btn btn-primary d-none cropped-only" hx-post="..." 
_="on htmx:afterRequest get detail.xhr.response.includes('success') then
      if it with <.avatar img/> set me.src to zu.imageCropper.objectURL then remove .d-none from me end"
>Confirm</button>
```
I tried replacing "with" with "tell" but "me" always refers to the "button" and not all occurrences of ".avatar img" on the page.
Am I missing something?

**Comment by 1cg** [comment]
Hi There,

Sorry about that! There was a semantic change when we went from `with` to `tell` because we wanted to keep `me` a stable reference to the "the current element" throughout the entire handler and avoid the problems javascript has with the `this` symbol.

I *believe* the code can be rewritten like so:

```
<button class="btn btn-primary d-none cropped-only" hx-post="..." 
_="on htmx:afterRequest 
               if detail.xhr.response.includes('success') 
                 tell <.avatar img/> 
                   put zu.imageCropper.objectURL into @src
                   remove .d-none"
>Confirm</button>
```

Would you mind testing it?  If this doesn't work, it should so I'll add a regression.  :)

Thank you for using hyperscript and pardon our dust!

**Comment by 1cg** [comment]
Hi There again,

I was noodling with this tonight and realized that I didn't get the logic in attribute references correct, so the code above will not work.  I have a fix in development and would like to get you a custom build so it works for you.  Let me know if that works.

Again, I really appreciate you using the language and I want to make sure it works properly for your use case!

**Comment by gmzu** [comment]
Hi There,
actually the code you suggested works correctly!
I don't know why you were convinced it wouldn't work, but it works!
Thanks so much

**Comment by 1cg** [comment]
Ah, I think because it is being used as with a `put`.  Unfortunately I believe if you *read* the attribute `@src` it will read from `me` rather than from `thingBeingTold`.  Just be aware of that until the next release, pardon our dust!
