### ISSUE TITLE
Using variables in expressions

### ISSUE THREAD

**Issue by jreviews** [bigskysoftware/_hyperscript#116]
Now that hyperscript has behaviors, it could be useful to support using variables within expressions to make them more configurable. For example. 

```html
<div data-hidden-class="hide"></div>
```

And then be able to use the defined `hidden-cass` within hs code.

```
set `.${@data-hidden-class}`
```

**Comment by wiverson** [comment]
I think that's the @data-hidden-class syntax? Or am I missing something?

**Comment by jreviews** [comment]
The attribute syntax works, but this was more related to behaviors https://hyperscript.org/docs/#behaviors

What I was trying to do here was to allow users define a dynamic class to represent a hidden state (display: none). On the hyperscript website, `hide` is used, but tailwindcss for example uses `hidden`. To make a headless behavior the behavior shouldn't have to know what the name of the hidden class is, it should be able to read it from the data-hidden-class attribute.

The example code above was for setting an element's class to the value found in the attribute, and that didn't work.

**Comment by dz4k** [comment]
This was added in 0.8.

```hyperscript
set .{@data-hidden-class}
```
