### ISSUE TITLE
The right way to use behaviors?

### ISSUE THREAD

**Issue by sianglim** [bigskysoftware/_hyperscript#117]
Hi,

I was playing with behaviors in _hyperscript@0.0.9, and I'm not sure what the expected way to write it is. Here's what I've tried.

If I add it into a script tag with `text/hyperscript`, and install it on an element, I get a `No such behavior defined as Removable Error: No such behavior defined as Removable` (e.g. using the Removable example in the docs at https://hyperscript.org/docs/#behaviors).

But if I add the behavior in the hyperscript attribute of an element, and add `install Removable`  it in any element after, it works?

**Comment by benpate** [comment]
Are you able to share sample code that demonstrates this problem?  It's possible that there's a timing problem with the remotely loaded script.  It would be easier to reproduce if we can see what you're seeing.

**Comment by sianglim** [comment]
Sure thing. I've attached two examples in the zip file.
[hyperscript-samples.zip](https://github.com/bigskysoftware/_hyperscript/files/6293187/hyperscript-samples.zip)

**Comment by dz4k** [comment]
This is a bug where script elements are processed after other elements, instead of all elements being processed in document order. It's fixed on the dev branch.

**Comment by benpate** [comment]
This fix should be in the latest release now, yes?  Is it possible to close this issue?

**Comment by dz4k** [comment]
@benpate Yes.
