### ISSUE TITLE
Trying to remove a class on click parsing error

### ISSUE THREAD

**Issue by jsantari** [bigskysoftware/_hyperscript#12]
Trying to use the following _="on click remove .hideme to #email-form" and it throws this error: Uncaught Error: Unexpected Token : to this is basically the same as one of the examples? Whats wrong with this?
[updated] Found that in another example it should have been from instead of to - however it would not work with #email-form id - had to add a class named email-form and then use .email-form as the from selector.

**Comment by 1cg** [comment]
I think the syntax is:

```
on click remove .hideme from #email-form
```

Does that work?

**Comment by jsantari** [comment]
Nope - will only work if I give it a class named .email-form and change the #email-form to .email-form

**Comment by 1cg** [comment]
Added a regression for this, works in 0.0.2
