### ISSUE TITLE
PROPOSAL: "global" keyword

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#122]
Does hyperscript need a `global` keyword?  HyperTalk had one, and it feels dirty to use `window.variableName` to define a value that's available everywhere.

```hyperscript
init
set global greeting to "yo"

on click from button "myButton"
set greeting to "mama"
```

**Comment by 1cg** [comment]
Another great idea, please add to TODO.md

**Comment by 1cg** [comment]
we have implemented this
