### ISSUE TITLE
PROPOSAL: date/time functions

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#123]
Without going overboard and re-developing something like [Moment.js](https://momentjs.com), I think Hyperscript could benefit from a few time/date commands.  It could easily be wrapped into its own separate package so that it doesn't affect people who don't need it.

Tag | Result | Example
--- | --- | ---
today | dateTime value of current day | 
tomorrow | dateTime value of next day |
yesterday | dateTime value of previous day |
now | dateTime value of current time |
before, after | modifies a dateTIme value | 1 day before today
from | same as `after` | 1 year from now
year, month, week, day, hour, minute, second | date range for  | 3 weeks after today\
is before, is after | date comparison function | if endDate is before 1 year from now then log endDate

**Comment by 1cg** [comment]
I like this idea, you can add it to the the TODO file
