### ISSUE TITLE
PROPOSAL: "play" command

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#124]
HyperTalk used `play` to trigger audio files.  Hyperscript could use this for audio (or possibly video) files as well.  This also sets a local variable called "the sound" that could be used to reference the audio after.

```
on click
    play /sounds/pop.mp3

on mousedown from AngerButton
    repeat until event mouseup
        play /sounds/klaxon.mp3
    end
    stop() the sound
```

**Comment by 1cg** [comment]
I love this idea.  I played around with the text-to-speech api to, but it doesn't work in chrome:

https://www.section.io/engineering-education/text-to-speech-in-javascript/

**Comment by 1cg** [comment]
Please add it to TODO.md
