### ISSUE TITLE
PROPOSAL: Cookies

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#128]
Can we implement a way to add/remove cookies in hyperscript?  This is similar to #127, but for stylesheets:

If we add expression `cookie` (similar to `tag`, `input`, or `button` from #121) that would identify a named cookie then we could do something like this:

```hyperscript
set cookie "theme" to "dark" expiring NEVER

fetch /signin
set cookie "authorization" to it expiring 1 hour from now

remove cookie "theme"
```

Again, this is a hot take on giving hyperscript the ability to manage stylesheets dynamically, and I'm happy to keep looking for better options.

**Comment by 1cg** [comment]
I like it!

**Comment by medihack** [comment]
Some cookie support in hyperscript would be great as it is one of the only reasons why I sometimes use Alpine.js + js-cookie instead of HTMX + hyperscript.
