### ISSUE TITLE
Putting and ajax response into an id using the id selector

### ISSUE THREAD

**Issue by jsantari** [bigskysoftware/_hyperscript#13]
Trying to use: _="on click ajax GET /main then put response into #main". This simply does not work? Doesn't seem to like the use of #main.

**Comment by 1cg** [comment]
Can you try:
```
on click ajax GET /main then put response into #main.innerHTML
```

**Comment by 1cg** [comment]
Hyperscript is *very* alpha, as you are finding out :)

Sorry, wish I had more time to put into it (as well as HTMX) but probably won't until mid fall.  :/

**Comment by jsantari** [comment]
That doesn't work either. For my use case I really don't need to use hyperscript to do what I wanted. Htmx code handled it fine. Great work up to this point with htmx. Hyperscript is very interesting in it's concept. Look forward to see more when you get to it.

**Comment by albert-kam** [comment]
Try `_="on click ajax GET /main then put response into main.innerHTML"`

**Comment by jsantari** [comment]
I tested it and that did work though I thought we tried that variation initially also. Odd thing is that it makes two ajax calls to /main - probably a bug which will get sorted out when the project gets worked on again as it's only an alpha.
