### ISSUE TITLE
Button onclick disabled example does not work

### ISSUE THREAD

**Issue by danihodovic** [bigskysoftware/_hyperscript#131]
Works in 0.0.8, broken in 0.0.9

![image](https://user-images.githubusercontent.com/5557301/115710953-9faaae00-a37b-11eb-93be-e9987d69b414.png)

**Comment by dz4k** [comment]
The syntax was changed to `[@disabled='true']`.

Your example can be updated as

```hyperscript
add [@disabled='true']
```

or

```hyperscript
set @disabled to 'true'
```
