### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by dz4k** [bigskysoftware/_hyperscript#140]
Right now, the formatting of the source is a mess. (This is mostly my fault). Different files are indented differently and core.js is a mix of spaces and tabs.

Here's a potential start:

```ini
root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.js]
indent_style = tab
tab_width = 4

[*.md]
indent_style = space
indent_size = 2
```

**Comment by benpate** [comment]
Yes.  Great idea.  Tabs > Spaces.  We could use the same config on htmx, too.
