### ISSUE TITLE
ajax doesnt add htmx request headers

### ISSUE THREAD

**Issue by albert-kam** [bigskysoftware/_hyperscript#15]
Hi, i did ajax using _hyperscript, and i notice the htmx request headers are not there yet.

Is this intentional or perhaps there is a way to get the headers sent ?

Thank you ...

**Comment by 1cg** [comment]
this is intentional: the ajax functionality in hyperscript is unrelated to htmx.

However, you can use hyperscript to trigger an htmx request via a custom event pretty easily:

```
  <button _='on click send myEvent to #div1'>Send Request<button>

  <div id='div1' hx-trigger='myEvent' hx-get='/example'>...</div>
```
