### ISSUE TITLE
Style literals

### ISSUE THREAD

**Issue by dz4k** [bigskysoftware/_hyperscript#151]
The `add` command can be used to add styles to elements. However, the syntax for this is a bit off:

<table>
<tr><th>real CSS<th><code>add</code> command
<tr><td><pre><code>{
  margin: 0 0 1em;
  border: 1px solid ${border-color};
}</code></pre>
<td><pre><code>{
  margin: "0 0 1em",
  border: `1px solid ${border-color}`
}</code></pre>
</table>

We should have a style literal syntax that mimics CSS to the maximum possible extent.

**Comment by 1cg** [comment]
merged and based and redpilled
