### ISSUE TITLE
Several documentation issues, e.g. settle -> 404 + inadequate example

### ISSUE THREAD

**Issue by trebor74hr** [bigskysoftware/_hyperscript#166]
Several issues I found in documentation:

1. https://hyperscript.org/docs/#default-commands row: 

`settle | Waits for a transition to end on an element, if any | set x to 0
`

has wrong example and clicking on it returns 404 - not found. 

2. The same thing is on https://hyperscript.org/reference/ - search for "settle".

3. Another one with wrong example: 

`tell | Temporarily sets a new implicit target value | with <p/> add .highlight`

btw. In this example command `with` is used and there is no such command explained.

4. This returns 404 too: 
relative positional expressions | Get a positional value out of an array-like object
https://hyperscript.org/expressions/relateivePositional

5. on https://hyperscript.org/talk/ link https://hyperscript.org/discord does not work (404)

**Comment by dz4k** [comment]
All are fixed.

**Comment by trebor74hr** [comment]
Great, that was fast :) One thing is left unfixed: on pages: https://hyperscript.org/docs/#default-commands and 
https://hyperscript.org/reference/#commands, command **settle** has wrong example in table row (given example is for **set** command):

  settle | Waits for a transition to end on an element, if any | **set x to 0**

**Comment by dz4k** [comment]
> One thing is left unfixed: on pages: https://hyperscript.org/docs/#default-commands and
> https://hyperscript.org/reference/#commands, command **settle** has wrong example in table row (given example is for **set** command):
> 
> settle | Waits for a transition to end on an element, if any | **set x to 0**

Fixed!
