### ISSUE TITLE
behavior with parameter not working

### ISSUE THREAD

**Issue by luheeslo** [bigskysoftware/_hyperscript#173]
Hi,

I implemented a following behaviour with parameter in my page:
```
<script type="text/hyperscript">
      behavior Focusable(inp)
        on focus from inp
          add .outline-none .border-gray-400
        on blur from inp
          remove .outline-none .border-gray-400
      end
 </script>
```
And installed it in my element:
```html
<div _="install Focusable(inp: #username)" class=". . .">
      <input type="text" value="" name="username" id="username" .../>
 </div>
```

But the browser console returns me a following error: `Cannot read properties of undefined (reading 'owner')`.

On the other hand, if I use positional expressions like this:
```
<script type="text/hyperscript">
      behavior Focusable
        on focus from first in me
          add .outline-none .border-gray-400
        on blur from first in me
          remove .outline-none .border-gray-400
      end
 </script>
```
And I remove the parameter list from div above,  its works.

Version: 0.8.1

**Comment by 1cg** [comment]
Hi There.  I am able to replicate the bug locally, and will try to get it fixed.

**Comment by 1cg** [comment]
I have merged a fix for this issue into dev, hope to have a new release soon
