### ISSUE TITLE
multiple event handler

### ISSUE THREAD

**Issue by jgirardet** [bigskysoftware/_hyperscript#177]
Hi, 
I was trying  to deal with 2 events handlers
I found `end` (in tests) which is undocumented.
 `<div _"on mouseenter toggle .active  end  on mouseleave toggle .active">...</div>`

But something like `on {mousenter, mouseleave} toggle .active` would be very cool and readable

thanks for _hyperscript
Jimmy

**Comment by dz4k** [comment]
In <https://hyperscript.org/features/on/>:
> Events can be repeated separated by an or to assign one handler to multiple events:
> ```html
> <div _="on click or touchbegin fetch /example then put it into my.innerHTML">
>   Fetch it...
> </div>

Later on the same page: 
> The `end` is optional if you are chaining on features together

**Comment by jgirardet** [comment]
oh I'm sorry. I read the full page tree times also...
Maybe we could add `aggregate event` like `mutation event` or `intersection event` to emphis it.
I'll push it if you're ok

**Comment by rtgoodwin** [comment]
As a newb I also wasn't clear on this. like if i wanted to do actions ABC on event1 but options XYZ on event2. I was thinking you'd do two `_=` (and maybe you can?) but the `end` is perhaps better in simpler situations. 

Seems to be easy and supported so maybe an example in docs would help. :)

**Comment by dz4k** [comment]
A lot of people seem to try adding multiple `_` attributes... I'd like to make that work, but it's not possible to have multiple of the same attribute in HTML :/

I'll add examples of both of these things in the docs, close to the start. Hopefully that will be enough to make it clearer.

@rtgoodwin, you don't need `end`. You can just put another `on` after the end of the first handler.
```hyperscript
on hover or focus
  call func1()
on submit
  call func2()
```

**Comment by 1cg** [comment]
Also, you don't need to use a `tell` command here, both remove and transition allow for specifying targets:

```html
 <div _="on mouseover
             remove .hidden from #catFilterSelect 
            transition #catFilterSelect's opacity to 1
           on mouseout
            hide #catFilterSelect"
            class="relative col-span-1 inline-block text-left">
```

If you did want to use `tell`, you'd probably only use one:

```html
 <div _="on mouseover
               tell #catFilterSelect
                  remove .hidden  
                  transition opacity to 1
               end
           on mouseout
            hide #catFilterSelect"
            class="relative col-span-1 inline-block text-left">
```

The `tell` command should respect new feature boundaries though...

**Comment by rtgoodwin** [comment]
Thanks a ton! I had to work on something else for a couple of days but will be diving back in :) Appreciate the examples and commit!
