### ISSUE TITLE
Support negative modifiers on class names (as in TailwindCSS)

### ISSUE THREAD

**Issue by rtgoodwin** [bigskysoftware/_hyperscript#185]
Currently, trying to pass a class name with `-` appended will cause an error. Per discussion on Discord this should be supported. 

Example that will fail: 
```
on change add .left-0 .-top-0 
```

For now using the excellent example provided of modifying `margin-top`.

**Comment by julianwachholz** [comment]
I think the most sensible solution is to support escaping special characters in classnames, since this is the same way Tailwind has to do it so browsers understand the syntax correctly:

```css
.w-\[50px\] { }
.p-0\.5 { }
.dark\:hover\:bg-gray-100 { }
```
