### ISSUE TITLE
0.8.2 doesn't seem to load anything, no error messages

### ISSUE THREAD

**Issue by rsyring** [bigskysoftware/_hyperscript#188]
I just updated a project to 0.8.2 and it appears non of the hyperscript code is running ~~in Firefox~~.  No errors in the web console, just nothing.  Bump back to 0.8.1 works.  ~~Open in Chrome works~~.

Thanks.  :)

Also, FYI, I'm loading with:

```
<script src="https://unpkg.com/hyperscript.org@0.8.2"></script>
```

Edit: my previous comment about working in Chrome was incorrect.  I was accidentally still working on 0.8.1 when I opened Chrome.

**Comment by dz4k** [comment]
Cannot reproduce on Firefox 94.0. Can you set up a public page to test?

**Comment by rsyring** [comment]
Thanks for the prompt reply.  I'll work on setting up a public test case.

**Comment by rsyring** [comment]
@dz4k I've added you to a private repository that have some file I extracted from the web app that this issue developed in.  There is nothing super sensitive there, but since it's an internal page of my client, I don't want it completely public.  If any other maintainers need access to that repo, just let me know.

**Comment by dz4k** [comment]
After inspecting the repo you've sent me, here are my findings:

- _hyperscript loads fine
- event handlers are added fine (you can see this in devtools)
- BUT: the `add` command doesn't work.

This is a really weird regression that we definitely have tests for... what is happening? the `add` command is somehow broken, did we not run tests? or is there something special about your website?

All of these are questions that I'll be asking myself as I look into the git log.

**Comment by dz4k** [comment]
Figured it out. The add command uses `runtime.forEach` when it should be using `runtime.implicitLoop`. This means that it was looping over the children of the form and adding the class to them, instead of the form itself. @1cg should I write a hotfix against master? This seems too important of a bug to wait for the next release.

**Comment by 1cg** [comment]
Yep, a hotfix is fine.  Create a branch w/ the fix and I'll publish it.

**Comment by dz4k** [comment]
https://github.com/bigskysoftware/_hyperscript/pull/189

**Comment by 1cg** [comment]
I will cut a bug fix release tonight

**Comment by 1cg** [comment]
cut the release, 0.8.3
