### ISSUE TITLE
Bug? Can't selectively `return` out of a function

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#193]
When a `return` statement is embedded in an `if` statement, it seems like it is still exiting the function incorrectly.

I've isolated this issue (I think) into the code below.  In the example, the first `return` should never happen, and the behavior *should* put "Success" into the parent element.  But the `return` is somehow executing even though it should be skipped, so the div still says "failure" instead of "success".

```html
<html>
<head>
    <script src="https://unpkg.com/hyperscript.org"></script>
    <script type="text/hyperscript">
        behavior fail
            init
                if false then
                    set my innerHTML to "never"
                    return
                end

                set my innerHTML to "Success?"
                return
            end
        end
    </script>
</head>
<body>
    <div _="install fail()">Failure :(</div>
</body>
</html>
```

**Comment by 1cg** [comment]
will debug today

**Comment by 1cg** [comment]
looks like a parsing issue, will try to fix and cut a 9.1 today

**Comment by 1cg** [comment]
confirmed issue w/ how we parse `return`

You can `return false` for now to fix it :expressionless: 

will fix in 0.9.1 release...

**Comment by 1cg** [comment]
lol, no, i just forgot

in hyperscript `return` always returns a value

if you want to return without a value, you use `exit`

the bug is that we should error out on the above code when `end` is encountered as an expression and suggest you use `exit` instead.  

Your code is parsing like so:

```applescript
        behavior fail
            init
                if false then
                    set my innerHTML to "never"
                    return end
                    set my innerHTML to "Success?"
                    return end
        end
```

Instead it should be:

```applescript
        behavior fail
            init
                if false then
                    set my innerHTML to "never"
                    exit
                end
                set my innerHTML to "Success?"
            end
        end
```

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/_hyperscript/commit/4e733e232980136c322578d872e93d5a360699cf

**Comment by benpate** [comment]
Phew!  Thank you!  Is this fix in Dev?

**Comment by 1cg** [comment]
yep
