### ISSUE TITLE
Broken link on the Docs (Set feature)

### ISSUE THREAD

**Issue by jorge-santos-porto** [bigskysoftware/_hyperscript#202]
In the Docs, [Set Feature](https://hyperscript.org/docs/#set_feature),
in the sentence "_The syntax is identical to the **set** command_"
**set** currently links to the broken link: [let](https://hyperscript.org/commands/let)
It should link to [set](https://hyperscript.org/commands/set)

**Comment by 1cg** [comment]
Thank you.  The docs have been rewritten so this is no longer an issue.
