### ISSUE TITLE
Bug Report: Problem with 'wait' command in behaviors

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#206]
I'm working on a behavior that will live-updates its element based on the current time.  But, I run into problems when when the behavior is installed on than one element on the page.  I've boiled this down to a problem with the `wait` command -- it seems to be applying across all behaviors on the page, *possibly because they're all running in a single thread*.

Here's my sample code:

```html
<!DOCTYPE html>
<html>
<body>

    <script type="text/hyperscript">
        behavior WeirdBehavior

            on load
                set my innerHTML to "Success!"
                wait 1s
                exit
            end
        end

    </script>

	<script src="https://unpkg.com/hyperscript.org"></script>

    <div class=date _="install WeirdBehavior">Broken?</div>
    <div class=date _="install WeirdBehavior">Broken?</div>
    <div class=date _="install WeirdBehavior">Broken?</div>
    <div class=date _="install WeirdBehavior">Broken?</div>
    <div class=date _="install WeirdBehavior">Broken?</div>
    <div class=date _="install WeirdBehavior">Broken?</div>

</body>
</html>
```

If the `wait` command is left in then only the first element will get processed, followed by the last element about a second later. But all of the others will remain "broken."  If I remove the `wait` command, then all behaviors run immediately, as expected.

This issue is too deep into the hyperscript internals for me to tackle with confidence, but I'm willing to take direction, or provide additional test cases if that would help to troubleshoot the problem.

**Comment by 1cg** [comment]
My guess is that all the behaviors are using the same event queue.

**Comment by benpate** [comment]
Yes. My hunch too.  Thanks for looking at this 😀 I did one other experiment, triggering a new event and putting all the "wait" logic in a separate handler. It didn't change the result. 

I'm not sure how JS event queues work, but I can read up and report back if I find anything new.

**Comment by 1cg** [comment]
Yep, that's the problem.  We need a distinct queue per on feature.

**Comment by 1cg** [comment]
Basically this logic needs to be tied to the element scope rather than to the feature scope:

https://github.com/bigskysoftware/_hyperscript/blob/be53c0c18b681b346699ebd76a4815b8be7251bf/src/lib/core.js#L3741

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/_hyperscript/commit/14e6cfd9e70571706b15260dd94b329aadda001c
