### ISSUE TITLE
Bug: Lazy evaluation of CSS literals has broken `no` and other expressions

### ISSUE THREAD

**Issue by ajusa** [bigskysoftware/_hyperscript#209]
The one that I mentioned on Discord is `no` https://hyperscript.org/expressions/no/. The docs example will never log the statement because it is always true. Similarly, is empty and is not empty have this issue.

Additionally, stuff like checking the length of a CSS literal statement doesn't work, eg `<button/>.length == 0`. I believe it throws an error during compile time.

**Comment by dz4k** [comment]
`is empty` and `is not empty` can be fixed by adding a `length` getter to the `ElementCollection` class. `no` is a bit harder though.

**Comment by 1cg** [comment]
`no` should use the length too, right?  It calls `_runtime.isEmpty()`

**Comment by ajusa** [comment]
This is fixed on dev, closing!
