### ISSUE TITLE
Escape colons for class literals breaks input pseudo selectors

### ISSUE THREAD

**Issue by jvosloo** [bigskysoftware/_hyperscript#211]
As per Discord chat, it seems like this method:

```
function escapeSelector(str) {
    return str.replace(/:/g, function (str) {
        return "\\" + str;
    });
}
```

breaks a query like this: `<input[name='reportFormat']:checked/>`

@1cg pointed to this place in code where this needs to be addressed:
![image](https://user-images.githubusercontent.com/180948/146362896-766519c7-b9b6-4089-8cfe-3cbdb565d96d.png)

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/_hyperscript/commit/fa7d739e6fa812ebf98013ca035acc5420cb39c6
