### ISSUE TITLE
Misspelt identifier error handling should be improved

### ISSUE THREAD

**Issue by jvosloo** [bigskysoftware/_hyperscript#219]
If you specify a command on an element (e.g. `show #myelement`) but you misspelt the target (e.g. it should be `#myElement` instead), you get a `Invalid value used as weak map key` error message.

It seems like a good idea to trap that error and report it in the console in a more user friendly manner, something like
`#myelement not found. Please check if the target exists in the DOM`

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/_hyperscript/commit/27952c361abcd05980dfeafbc810a0baeca94bd1
