### ISSUE TITLE
Error in Docs

### ISSUE THREAD

**Issue by stevenjwright** [bigskysoftware/_hyperscript#22]
Hey there, 

There's an error in the following example page: https://hyperscript.org/commands/remove/

`<div _="on click remove .not-clacked to #another-div">Remove Class From Another Div!</div>`

I think the `to` should be `from`, so:

`<div _="on click remove .not-clacked from #another-div">Remove Class From Another Div!</div>`

Thanks!

**Comment by 1cg** [comment]
Thank you, this is now fixed.
