### ISSUE TITLE
.data.name not working

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/_hyperscript#220]
The following code is not working as expected, as `me.data.test` is evaluated to `undefined`.

```
<div id="d" data-test="ok" _="on load log me.data.test"></div>
```

Whereas this does work.

```
<div id="d" data-test="ok" _="on load log me@data-test"></div>
```

**Comment by dz4k** [comment]
The first one is incorrect, it should be `me.dataset.test`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

However, if you want a shorter syntax for accessing data attributes, we could add something. Maybe `@@test`?

**Comment by bencroker** [comment]
Ah that makes sense, I must have misinterpreted the cheatsheet property access. Thanks for clarifying!

<img width="568" alt="Screenshot 2021-12-20 at 16 52 11" src="https://user-images.githubusercontent.com/57572400/146803392-db058d9b-6525-4182-b419-cb79125ef2c4.png">
