### ISSUE TITLE
PROPOSAL: Complete URLs in socket feature

### ISSUE THREAD

**Issue by zigellsn** [bigskysoftware/_hyperscript#221]
Hyperscript should complete WebSocket URLs in the socket feature the same way htmx does (see PR [#382](https://github.com/bigskysoftware/htmx/pull/382) by @srkunze):

- If no host and port is provided, use the current one
- For http use ws, for https use wss

I've already tried it and could open a PR, if that's okay.

Thank you for this wonderful library!

**Comment by benpate** [comment]
Hey @zigellsn --

Yes, that's a great idea.  Handling *should* be consistent between the two libraries.  At some point in the future, I'd love to give htmx the ability to plug into the hyperscript implementation of web sockets (and SSE, too).  Consistency in their behaviors will be important for making this seamless.
