### ISSUE TITLE
How to include minimally necessary js locally (witout unpkg ref) - which files?

### ISSUE THREAD

**Issue by jeanmonet** [bigskysoftware/_hyperscript#233]
Hi,
I would like to do as with htmx and include the minimally necessary .js (locally), ie `htmx.min.js`.

What would I need to download and include locally for hypescript? https://unpkg.com/browse/hyperscript.org@0.9.3/dist/

Is `_hyperscript_web.min.js` sufficient?

The documentation doesn't seem to specify this. Thank you!

**Comment by dz4k** [comment]
> Is `_hyperscript_web.min.js` sufficient?

Yes, it's sufficient. But I recommend adding <code>_hyperscript_web.min.js<strong>.map</strong></code> as well, so that we can debug any issues you have.

**Comment by jeanmonet** [comment]
Many thanks for confirming!

**Comment by jeanmonet** [comment]
Wanted to add that hyperscript is just amazing !!
