### ISSUE TITLE
Toggle div content

### ISSUE THREAD

**Issue by k1mbl3** [bigskysoftware/_hyperscript#234]
Is there any way to toggle div content instead of their classes?

**Comment by 1cg** [comment]
can you give me an example?

do you mean visibility?

**Comment by sdmcallister** [comment]
I'm not sure if this is what was meant, but I wondered about an easy way of toggling innerHTML. Something like this:

```
<button _="on click toggle 'Disabled' on my innerHTML">Submit</button>
```

**Comment by ab623** [comment]
But this is just the same as adding the disabled attribute to the DOM node itself. So it's not totally clear on what the use case is.

**Comment by 1cg** [comment]
this would probably be best achieved by storing a bit of state on the element in question and toggling it
