### ISSUE TITLE
Adding attributes with dashes in the name does not work

### ISSUE THREAD

**Issue by zilti** [bigskysoftware/_hyperscript#26]
Doing something like `add [my-attribute='value']` fails with an error:
```
Uncaught Error: Expected ']' but found '-'

on htmx:beforeRequest add [my-attribute='value']
                              ^^
```

**Comment by 1cg** [comment]
Ah, yeah, that's because hyperscript is tokenizing that as 

```
[my] [-] [attribute] [=]
```
I need to do context-sensitive token consumption inside of property literals.  

Unfortunately I probably won't have time to work on hyperscript for a few weeks.  Are you interested at all in taking a shot at it?

**Comment by zilti** [comment]
Well, maybe in about a week, maybe. I've done context-sensitive tokenization before. That can get a bit messy...

**Comment by 1cg** [comment]
I have fixed this issue in the dev branch.
