### ISSUE TITLE
Hyperscript unpkg sourceMappingURL 403

### ISSUE THREAD

**Issue by bennettscience** [bigskysoftware/_hyperscript#270]
I just noticed that the source map URL in the unpkg distribution has an invalid `sourceMappingURL` error in the console:

DevTools failed to load source map: Could not load content for https://unpkg.com/_hyperscript_web.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

The correct address is

`https://unpkg.com/hyperscript.org@0.9.5/dist/_hyperscript_web.min.js.map`

**Comment by 1cg** [comment]
we don't have source maps declared in our package....
