### ISSUE TITLE
PROPOSAL: Allow more than two dashes to be a comment

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#292]
Unlike most developers, I love comments 😉 and I love big comment headings like this

```
--------------------------------------------
-- HERE IS MY UGLY COMMENT HEADING
--------------------------------------------
```

Currently, hypersrcipt doesn't let you do this, as comments can only be started with *exactly two* dashes.  How difficult is it to update the parser to allow two *or more* dashes to initiate a comment?

**Comment by gnat** [comment]
Upcoming in dev, can be closed.
