### ISSUE TITLE
Single Quote (') in InnerHtml or in Any Value Gives error

### ISSUE THREAD

**Issue by mentotong** [bigskysoftware/_hyperscript#298]
hyperscript errors were found on the following element: 
<div id="main-content-wrapper" class="content-wrapper" _="on load put 'Atualiza - …e - HNGV' into <title/>"> 

 Expected one of 'into', 'before', 'at start of', 'at end of', 'after'

on load put 'Atualiza - Giacobo O'Dee - HNGV' into <title/>

**Comment by dz4k** [comment]
You can replace the string's quotes double quotes or backticks (double quotes might clash with HTML attribute quotes):

```
on load put `Atualiza - Giacobo O'Dee - HNGV` into <title/>
on load put "Atualiza - Giacobo O'Dee - HNGV" into <title/>
```
