### ISSUE TITLE
show and hide

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/_hyperscript#3]
Can you add `show` and `hide`

**Comment by chg20** [comment]
This should work:

```html
  <div _="on click set my.style.display to 'none'">Hide Me</div>
```

**Comment by sirinath** [comment]
There are multiple ways to do this now but it will be more natural to say `<div _="on click hide me">Hide Me</div>` and `<div _="on click show .cat">Show me the cat</div>`. `show` and `hide` be relatively frequantly  used.

**Comment by 1cg** [comment]
as of 0.0.4, hyperscript supports show and hide commands:

https://hyperscript.org/commands/show/

https://hyperscript.org/commands/hide/
