### ISSUE TITLE
errors in the documentation about Arrays

### ISSUE THREAD

**Issue by jfbouzereau** [bigskysoftware/_hyperscript#303]
The examples of first,last and random are erroneous. They should be 

log the first of myArr
log the last of myArr
log random in myArr

**Comment by dz4k** [comment]
Where are these examples?

**Comment by jfbouzereau** [comment]
In the documentation file https://github.com/bigskysoftware/_hyperscript/blob/master/www/docs.md

But obviously the errors have been fixed by commit 
ca8b20124cbd6b4060ad37e3e78b42c8305f8ec7

**Comment by dz4k** [comment]
Always annoying when issues don't get closed when they're fixed... Thanks for reporting!
