### ISSUE TITLE
bug - fetch doesn't read variables and uses their names instead of their values

### ISSUE THREAD

**Issue by malmiteria** [bigskysoftware/_hyperscript#304]
title.

this :
```
set element url to '/test'
on click fetch url end
```
visits /url, instead of /test

same applies with fetch inside a behavior so it makes refactoring fetch calls impossible :/

**Comment by dz4k** [comment]
This is the documented behavior. We're considering changing it, but it's would take a lot of refactoring if we did.

In the meantime, use a [template string](https://hyperscript.org/docs/#strings):

~~~
set element url to '/test'
on click fetch `${url}` end
~~~
