### ISSUE TITLE
Documentation needed for using template tags

### ISSUE THREAD

**Issue by EzzatOmar** [bigskysoftware/_hyperscript#31]
I'm using alpine with htmx/hyperscript.
I noticed that if I add htmx via the template tag the components are not initialized.
E.g.
```html
<template x-if="popup === 'signup'">
    ... HTMX ...
</template>
```
  
It is important to init HTMX/Hyperscript via
```javascript
htmx.process(addedTemplateTag);  
_hyperscript.processNode(addedTemplateTag);
```
  
  It would be nice to have this documented for future users. Also is it possible to reduce both process calls into one?
  One suggestion could be for html to check if _hyperscript is present and call processNode.
  
  Thank you

**Comment by 1cg** [comment]
I have added some documentation on 3rd party libraries:

https://htmx.org/docs/#3rd-party

In theory, just initializing with htmx should initialize hyperscript as well:

https://github.com/bigskysoftware/_hyperscript/blob/ddfa6bb1fd786784af41c662e34f08a0e01caf0d/src/_hyperscript.js#L3693
