### ISSUE TITLE
adding an elif (or elsif) clause to the if control flow command

### ISSUE THREAD

**Issue by malmiteria** [bigskysoftware/_hyperscript#310]
as seen in the doc : https://hyperscript.org/commands/if/ there's no elif clause for the if statement, meaning that today you can endup writing something like this

```
if <condition 1>
    <command list>
else
    if <condition 2>
        <command list>
    end
end
```

which feels a bit awkward compared to

```
if <condition 1>
    <command list>
elif <condition 2>
    <command list>
end
```

It would be nice to have acces to that.

An alternative (that might be easier to implement, depending on the current implementation of ifs) would be to be able to chain else if, without having to write the two end :

```
if <condition 1>
    <command list>
else if <condition 2>
    <command list>
end
```
which today leads to an error ```Error: Expected 'end' but found 'else'```

**Comment by 1cg** [comment]
i chose violence: if the `if` token is on the same line as the `else` token it is consider an `elseif` otherwise it is considered and `else` with an `if` statement within it:

https://github.com/bigskysoftware/_hyperscript/blob/16572f035b274d3027088715272e9e8066344196/src/_hyperscript.js#L5608
