### ISSUE TITLE
PNPM Cannot Create link to _hyperscript in node_modules/.bin

### ISSUE THREAD

**Issue by PapiPeppers** [bigskysoftware/_hyperscript#321]
Noticed this when upgrading to 0.9.7. PNPM upgrades, but warns that the hyperscript module has not been placed into the pnpm /bin. In your package.json, the "bin" section needs to remove the /bin/ from within "src/bin/node-hyperscript.js." Once I made this change, pnpm functioned without issue and hyperscript gets copied into the bin.

![20220718-230331](https://user-images.githubusercontent.com/57047860/179657223-0b18e9b1-d743-499e-abf8-9d2c2bfc409a.png)

**Comment by DmytroLitvinov** [comment]
We can't install via NPM 0.9.6 and 0.9.7 version because that was broken in that commit https://github.com/bigskysoftware/_hyperscript/commit/ccadc2cc2df981fc6d9db927753a059b69aa418c.

**Comment by lnoss** [comment]
I encountered the same problem today with pnpm v8.9.2.
```bash
WARN  Failed to create bin at C:\Users\...\node_modules\.bin\_hyperscript. ENOENT: no such file or directory, stat 'C:\Users\...\node_modules\hyperscript.org\src\bin\node-hyperscript.js.EXE'
```
