### ISSUE TITLE
Unable to set variables or log to console from <script> tag

### ISSUE THREAD

**Issue by kartzke** [bigskysoftware/_hyperscript#327]
Hi, I am trying to use HyperScript to construct a JSON object based on some `input` fields.  But I am not able to get the simple example from the [docs](https://hyperscript.org/docs/#properties) working.   I have this in my HTML:

```
<head>
    <script src="https://unpkg.com/htmx.org@1.8.0"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
</head>
<body>
    <script type="text/hyperscript">
        set x to {name : "Joe", age: 35}
        log x.name
        log x['name']
    </script>
</body
```

But console shows the following error:
```
hyperscript.org@0.9.7:1 hyperscript errors were found on the following element: script 

 variables declared at the feature level must be element scoped.

    log x.name
     ^^
 Error: variables declared at the feature level must be element scoped.

    log x.name
     ^^
    at a.raiseParseError (https://unpkg.com/hyperscript.org@0.9.7:1:11785)
    at a.raiseParseError (https://unpkg.com/hyperscript.org@0.9.7:1:11843)
    at https://unpkg.com/hyperscript.org@0.9.7:1:55181
    at n (https://unpkg.com/hyperscript.org@0.9.7:1:11188)
    at https://unpkg.com/hyperscript.org@0.9.7:1:8747
    at a.parseElement (https://unpkg.com/hyperscript.org@0.9.7:1:10515)
    at a.requireElement (https://unpkg.com/hyperscript.org@0.9.7:1:10706)
    at https://unpkg.com/hyperscript.org@0.9.7:1:47578
    at a.parseElement (https://unpkg.com/hyperscript.org@0.9.7:1:10515)
    at a.parseHyperScript (https://unpkg.com/hyperscript.org@0.9.7:1:11895)
```

Since this is all contained within the `<script>` tag, is the `x` variable scoped locally or at the element level?  Either way, the issue persists if I try to declare the variable at the element or global levels.  

(I'm not sure if log should use `:x` or just `x`, but I tried it both ways, same for global `$x`)

```
<script type="text/hyperscript">
    set :x to {name : "Joe", age: 35}
    log :x.name
    log :x['name']
</script>
```
```
<script type="text/hyperscript">
    set $x to {name : "Joe", age: 35}
    log $x.name
    log $x['name']
</script>
```

And just to sanity check, I confirmed HyperScript is working.  This triggers an alert prompt:

```
<div _="on click call alert('You clicked me!')">
  Click Me!
</div>
```

Am I doing something wrong, or is this a bug?

**Comment by rozek** [comment]
Well,

I'm new to \_hyperscript myself, but I've also already run across the limitation, that all elements of the kind `<script type="text/hyperscript">` must be placed **before** the `<script>` element which loads \_hyperscript

**Comment by kartzke** [comment]
> 

Thanks for the quick suggestion.  I tried putting the inline script above the CDN reference, like below.  I tried moving this to the `<head>` and the `<body>`, but I still get the same errors in both places.   Also tried `log $x.name`... no dice. 

```
   <script type="text/hyperscript">
        set $x to {name : "Joe", age: 35}
        log x.name
    </script>
    
    <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
```

**Comment by rozek** [comment]
But that's simple. Just change your code to

```
  init
    set $x to {name : "Joe", age: 35}
    log $x.name
  end
```

and don't forget `$` in front of the second `x`

With greetings from Germany,

Andreas Rozek

**Comment by rozek** [comment]
By the way,

I just _checked_ if `<script type="text/hyperscript">` elements _really_ have to be placed before `<script src="https://unpkg.com/hyperscript.org@0.9.7"></script>` - and **they have not**!

That means: its fine to append `<script type="text/hyperscript">` elements to the end of a document body!

**Comment by kartzke** [comment]
Awesome, it works now!  Thanks for the help with this.  🍻
