### ISSUE TITLE
[Bug] "element ElementVariable" and ":ElementVariable" differ

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#336]
The following code

```
<div _='
  init
    set element ElementVariable to `element variable w/o :`
    set :ElementVariable to `element variable w/ :`

    if (element ElementVariable == :ElementVariable)
      put `"element ElementVariable" is equivalent to ":ElementVariable"` into #ElementOutput
    else
      put `"element ElementVariable" differs from ":ElementVariable"` into #ElementOutput
    end
  end
'></div>
<div id="ElementOutput"></div>
```

shows that `element ElementVariable` and `:ElementVariable` refer to different variables

A live example can be found [here](https://svelte.dev/repl/9680660ba5e9445cbae880483f983e85)

**Comment by dz4k** [comment]
The sigil is part of the name. It seems this was never documented as clearly as it should have

**Comment by rozek** [comment]
Indeed, that's **very** important - and not really intuitive (not for me, at least)
