### ISSUE TITLE
"local FeatureVariable" differs from local Variable

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#337]
The following may not be a bug, but I do not really see why the given variables differ in their scope.

The following code 

```
<div _='
  init
    set localVariable to `localVariable`
    set local FeatureVariable to `FeatureVariable`

    if (local FeatureVariable == :localVariable)
      put `"local FeatureVariable" is equivalent to "localVariable"` into #FeatureOutput
    else
      put `"local FeatureVariable" differs from "localVariable"` into #FeatureOutput
    end
  end
'></div>
<div id="FeatureOutput"></div>
```

shows that local variables created without any prefix differ from those created with a `local` prefix.

If they differ by purpose, this detail should be clearly explained in the docs.

A live example may be found [here](https://svelte.dev/repl/be33b85910f44d76bef5ef1c6523fc09)

**Comment by dz4k** [comment]
I don't get what the problem is here. You set two local variables to different values, and they are not equal. What was the expected behavior?

You are also trying to access `:localVariable` with a colon, which is undefined.

**Comment by rozek** [comment]
Indeed, the colon was wrong - but even without a colon, the problem persists: if `local x` and `x` would refer to the same variable, the comparison would yield true.

**Comment by rozek** [comment]
Damn...I found my mistake (must have been blind) Sorry for bothering you!

**Comment by dz4k** [comment]
Why would the comparison between `localVariable` and `FeatureVariable` be true?

This works as expected:

```
<script type=text/hyperscript>
  init
    set x to 1
    set local x to 2
    put (x == local x) as String after me
</script>
```

**Comment by dz4k** [comment]
Oh, just saw you closed this

**Comment by rozek** [comment]
Yes, it's been my fault - sorry for wasting your time!
