### ISSUE TITLE
how can one send data within a request body using "fetch"?

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#339]
The title already describes the problem:

how can "fetch" send some data as part of a request's body to a server?

I tried

```
    on fetch:beforeRequest (headers, body)
      set headers['Content-Type'] to 'application/x-www-form-urlencoded'
      set body to 'email=a.b@c.de'
    end
```

but - according to the networking log in browser's developer tools - that did not actually provide a body

**Comment by dz4k** [comment]
The `fetch` command supports all options of the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/fetch):

```
fetch /path with body: 'email=a.b@c.de', headers: { content-type: 'application/x-www-form-urlencoded' }
```

**Comment by rozek** [comment]
Great! Thank you very much!
