### ISSUE TITLE
[Bug] double slashes in template strings are treated as comments

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#341]
The following code

```
    def hugo (Argument)
      log Argument
    end

    init                  -- see https://kvdb.io/ for this example based on curl
      put 'Path' into Path
      hugo(`https://server.de/${Path}`)
    end
```

logs `https:` rather than `https://server.de/Path`

a live example can be found [here](https://svelte.dev/repl/c85aa60508e7437da19040295c3a1790)

**Comment by gnat** [comment]
Seems to effect all comment types (`--`, `//`, `/* ... */`) if enclosed in backtick strings within a block.

`"` and `'` work as intended, though.

We're just not ignoring comments fully when using backtick strings, it seems.

Thanks for the catch.
