### ISSUE TITLE
[Doc] incomplete description "hide"

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#343]
in [the docs for `hide`](https://hyperscript.org/commands/hide/) what do

* `[: <argument>]` and
* `[when <expr>]`

mean?

Addendum: I meanwhile found a description in [the docs for `show`](https://hyperscript.org/commands/show/). Is that also valid for `hide`?

**Comment by dz4k** [comment]
> Addendum: I meanwhile found a description in [the docs for show](https://hyperscript.org/commands/show/). Is that also valid for hide?

Yep. Mind adding a link to the `show` docs in `hide`?
