### ISSUE TITLE
[Doc] block literals

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#346]
Shouldn't ["block literals"](https://hyperscript.org/expressions/block-literal/) be better called "lambdas"? According to the description, they _are_ in fact anonymous functions

**Comment by gnat** [comment]
"block literal" is a self-describing name when combined with the 1 line of documentation.

We shouldn't have to give a history lesson or background in "what does lambda mean?" when the 1 line in the docs works perfectly fine.
