### ISSUE TITLE
[Request] please remove file "/dist/_hyperscript.d.ts"

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#353]
What is an empty TypeScript definition file good for? Its presence suggests some TypeScript compatibility - but that's not true.

Thus, please either fill it with real definitions (that would be fine) or just remove it

**Comment by FDiskas** [comment]
exactly
![image](https://github.com/bigskysoftware/_hyperscript/assets/468006/375532d1-0a52-4185-917a-56bb29ef1318)
