### ISSUE TITLE
Questions about _hyperscript.js

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#357]
I'm currently trying to "convert" \_hyperscript.js to TypeScript because

* TypeScript finds so many typos that the actual testing effort is drastically reduced and
* TypeScript cross-compiles to a JavaScript version which may also be run on older devices and browsers

During this process (which may even fail if the effort is too high) I'm running across many problems - some of them may be solved by looking at the code. but others are not.

Here are my questions:

* line 2311: ElementCollection constructor - is `escape` optional?

More questions may follow...

**Comment by rozek** [comment]
Note: in order to complete my TypeScript port I made `escape` optional

**Comment by 1cg** [comment]
I think this is a good project for typescript, but we aren't gonna port any time soon unfortunately.  (time and money)
