### ISSUE TITLE
[Announcement] experimental TypeScript port of _hyperscript

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#358]
Because of problems with the (quite modern) JavaScript code of \_hyperscript on older browsers, I have started an experimental port to TypeScript. Being a cross-compiler, TypeScript not only performs extensive code checks but also generates JavaScript code which may run on older devices.

The code may be found in the "dev" branch(!) of [my fork of \_hyperscript](https://github.com/rozek/_hyperscript/tree/dev) and may be used by inserting

```
<script src="https://unpkg.com/hyperscript-experimental"></script>
```

rather than the original.

And please, don't blame [Big Sky Software](https://github.com/bigskysoftware) for the mistakes **I** may have made by porting...

**Comment by rozek** [comment]
FYI: I've just changed my \_hyperscript examples (see [here](https://github.com/rozek/hyperscript-examples)) in order to run them using my port - and they seem to work like with the original code

**Comment by rozek** [comment]
Good morning!

I've migrated everything until before `hyperscriptCoreGrammar` so far (approximately one third?)

**Comment by 1cg** [comment]
leaving as JS for now
