### ISSUE TITLE
question about variable scoping

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#360]
let's assume that there is a behavior B used by multiple DOM elements.

Will a "local" variable V then be shared among usages of B (similar to a static class variable in JS)?
Will individual variables have to be element-scoped (like non-static class variables in JS)?

**Comment by dz4k** [comment]
Local variables (those declared with no sigil) will never be shared.

Element-scoped variables (declared with `:`, or top-level `set`) will be shared across handlers on an element. However, behaviors will be isolated from each other and the element's inline code. This is to avoid name collisions.

If you install a behavior in multiple places, they will not share `:`-variables.

Does this answer your questions?

**Comment by rozek** [comment]
Yes, indeed, thanks.

The important phrase was "...behaviors will be isolated from each other and the element's inline code..."
