### ISSUE TITLE
Short circuiting logical connectives

### ISSUE THREAD

**Issue by jkseppan** [bigskysoftware/_hyperscript#363]
The documentation says "Comparisons can be combined via the and, or and not expressions in the usual manner". I thought the usual manner was to not evaluate the right-hand side when the result is determined by the left-hand side, but apparently not:

https://jsfiddle.net/_jks/rf74xdbe/

If short-circuiting AND and OR is not considered suitable, how about AND THEN and OR ELSE? At least AND THEN is not currently a parse error but it doesn't do short-circuiting evaluation.

**Comment by 1cg** [comment]
Unfortunately this is a consequence of the async transparency in the runtime.  Same thing with parameter evaluation.  I'll make a note of it in the docs.  😑

**Comment by 1cg** [comment]
I decided to make this work properly in hyperscript, at least in the synchronous case
