### ISSUE TITLE
remove from children of `#id`?

### ISSUE THREAD

**Issue by SHxKM** [bigskysoftware/_hyperscript#368]
Great work here, this + HTMX is awesome.

I haven't been able to find a way to remove all child divs of a certain element with an ID.

```
then remove allChildren of #the-id
then remove allChildren from #the-id
then remove innerHTML from #the-id
```

All these return an `is null` error in the console.

Update:

This is doing nothing either:

```
then remove <div#id.some-class-added-just-to-remove/>
```

**Comment by SHxKM** [comment]
Sucking at CSS, UI is exactly why I'm using these libraries, the correct selector is of course:

```
<div#id .some-class-added-just-to-remove/>
```

I wonder if there's a more `hyperscript` way to do it though? Anyway, this is not an issue.

**Comment by dz4k** [comment]
You could write `.some-class-added-just-to-remove in #id`, if you so desire

**Comment by chuan137** [comment]
can we reopen this issue?

imo, the use case is a valid one. Using such expressions (readable, natural) avoids making references from various places, which should be the more appealing pattern, like what is claimed in the doc "de-emphasize [Separation of Concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) in favor of [Locality of Behavior](https://htmx.org/essays/locality-of-behaviour/)."

imagin another request that updates the div, you will have to maintain the class of divs all over of places in the code.

**Comment by dz4k** [comment]
```
remove children of #id
```

https://developer.mozilla.org/en-US/docs/Web/API/Element/children

**Comment by chuan137** [comment]
@dz4k thanks for the response, but it didn't work for me, is this the right way to use the expression?

`      <button type="submit" _="on click remove children of #share-summary">Search</button>
`
