### ISSUE TITLE
Javascript functions with numbers in name return "Must be a function invocation" error

### ISSUE THREAD

**Issue by Nicero** [bigskysoftware/_hyperscript#373]
**_hyperscript v0.9.7**

I noticed this strange behaviour and I don't know if I doing something wrong or it's a bug.

If a Javascript function has a number in its name _hyperscript returns the error _Must be a function invocation_. 

Take for example the following code: the value of the first `INPUT` is sent to the function `text101` which simply returns the same string which is `put` as value of the second `INPUT`.

_hyperscript returns _Must be a function invocation_ error.

If you rename the function removing the number '101', the code works properly.

    <input id="one" type="text" 
        _="on keyup call text101(my.value) then put result into #two.value">

    <input id="two" type="text">

    <script type="text/javascript">
        function text101(s) {
            return s;
        }
    </script>

**Comment by 1cg** [comment]
Sounds like a lexing error, I will look at it for the next release

**Comment by 1cg** [comment]
We have a test verifying this works:

https://github.com/bigskysoftware/_hyperscript/blob/d5da09ea618fc18a0cc0de141a7433212c808d0c/test/core/regressions.js#L132
