### ISSUE TITLE
Simple trigger example from docs does not work

### ISSUE THREAD

**Issue by Ramblurr** [bigskysoftware/_hyperscript#388]
The second example on the docs for [send/trigger](https://hyperscript.org/commands/send/) does not work:

## Repro
```html
<head>

<script src="https://unpkg.com/hyperscript.org@0.9.7"></script>

</head>
<body>
<div _="on click trigger doIt(answer:42)
        on doIt(answer) log `The answer is $answer`">
  Click Me!
</div>
</body>

```
or [fiddle](https://jsfiddle.net/w2d6t9gf/)

## Result

![scrn-2022-10-14-15-46-03](https://user-images.githubusercontent.com/14830/195862548-a52668cb-cf23-4a43-8106-701acbeca411.png)

**Comment by 1cg** [comment]
good catch!
