### ISSUE TITLE
"Values" conversion not getting selected values from multiple-select form field

### ISSUE THREAD

**Issue by rogue26** [bigskysoftware/_hyperscript#391]
I have a form with a combination of single-select and multiple-select fields. The Values conversion works perfectly for grabbing the values from the single-select fields, but returns an empty array for multi-select fields, regardless of whether any items are selected or not.

The only difference between the fields is the presence of the "multiple" attribute, and when I manually remove it, Values grabs the correct values.

I'm happy to help with any testing that's necessary.

**Comment by 1cg** [comment]
we have a test for this now, should work:

https://github.com/bigskysoftware/_hyperscript/blob/532ec2b0b86be1b360ab844b73186748fbf659a0/test/expressions/asExpression.js#L185
