### ISSUE TITLE
Event filter syntax on intersection synthetic event

### ISSUE THREAD

**Issue by ewired** [bigskysoftware/_hyperscript#394]
Using the event filter syntax with `intersection` like `on intersection[intersecting]` isn't firing, but it does fire when I explicitly destructure it out of the event like `on intersection(intersecting)[intersecting]`.

**Comment by c-nv-s** [comment]
another example... attempting to use ``intersection`` with a count filter when trying to get the event to only fire once..
```
_='on intersection(intersecting) 1 having threshold 0.5
    if intersecting alert("element now in view") end'
 ```
 does not work

**Comment by 1cg** [comment]
turns out the reason this isn't working is because `detail` properties are not available in the filter expression like they are in the destructuring syntax.  I have fixed that assymetry with 

https://github.com/bigskysoftware/_hyperscript/commit/15136a88f1ee1272d77c230855853840465ff494
