### ISSUE TITLE
Sending events from JavaScript

### ISSUE THREAD

**Issue by cemrehancavdar** [bigskysoftware/_hyperscript#398]
Hi,
I have two questions: 
I think there is no direct way to send an event from JavaScript directly to and element. I've managed it by using _hyperscript function but it doesn't seem to good practice to me. I didn't want to wrap it myself with exceptions and smth. What is best way to to it?
The script:
_hyperscript("init send showMessage(message:'Message from JS!') to #output")

Second question is, how to deal with any other library events like on zoom, on draw or smth?

**Comment by 1cg** [comment]
sending events is annoying in javascript, but not terrible:

```js
const event = new Event('example');
elem.dispatchEvent(event);
```

I wouldn't use hyperscript just to do that.  htmx also has a `trigger()` function you can call if you are mixing it in with hyperscript.

hyperscript should be able to listen for any event triggered by libraries so long as they use the standard javascript event mechanism.  nothing special about it.
