### ISSUE TITLE
[Bug] "Making" an element and "appending" it doesn't work

### ISSUE THREAD

**Issue by iamjameswalters** [bigskysoftware/_hyperscript#403]
The [docs for `make`](https://hyperscript.org/commands/make/) provide an example of using `make` to create a DOM element then `append` it to the page. However, this puts a string representation of the object in the page, rather than the element.

I ran into this on a project I was working on, but I don't have that code handy at the moment. 

Instead, I took the example code and added the missing, assumed pieces (i.e., styles and arguments):

```
<style>
.toppings {
  color: red;
}
</style>

<script type="text/hyperscript">
def formatPizzaToppings(toppings)
  make an Intl.ListFormat from "en", { type: "conjunction" }
    called listFmt

  for part in listFmt.formatToParts(toppings)
    if the part's type is "element"
      make a <span.topping/>
      put the part's value into its textContent
      append it to #toppings
    else
      append the part's value to #toppings
    end
  end
</script>

<div id="toppings" _="init formatPizzaToppings(['Pepperoni', 'Mushrooms', 'Green Peppers'])">
</div>
```

and loaded it into the [playground](https://hyperscript.org/playground/). 

I should have got this, per the docs:

![image](https://user-images.githubusercontent.com/33947683/209240469-ddcdef9c-8e42-46e5-bcf0-4ee5ea2906f5.png)

But instead, I got this:

![image](https://user-images.githubusercontent.com/33947683/209240423-f16ec1a3-c59f-453c-9fc6-fe302f88352b.png)

**Comment by hakanoktay** [comment]
There is already a documentation that is difficult to read, difficult to understand, almost without examples, based on the imagination and knowledge of someone who has not yet learned what to do and how to do it. I am about to give up. 

and I think they have a community that doesn't like to answer.

**Comment by andryyy** [comment]
Append will append a string to an element.

You want to `put element at end of #there`

**Comment by iamjameswalters** [comment]
@andryyy That's one way to do it, yes. But per [the docs](https://hyperscript.org/docs/#strings), `append` also appends to HTML content or the DOM:

> The [append](https://hyperscript.org/commands/append) command can append content to strings (as well as to arrays and the DOM)

Per the [append reference](https://hyperscript.org/commands/append/):

> The append command adds a string value to the end of another string, array, or HTML Element.

And again, I was following the example code from the [make documentation](https://hyperscript.org/commands/make/).

**Comment by andryyy** [comment]
Hm, it says:

  The append command adds a **string value** to the end of another string, array, or HTML Element.

That confirms my assumption.

The example makes a span element and has the parts value set to its textContent. 

I assume that if you set the elements textContent you can append it as text to another element. If it doesn’t have textContent, it will parse the node as string. 

You may also use element.outerHTML and append it to another element, but this will just append the text of the outerHTML to it. :)

_hs’ append is different from JS‘ append. It’s just a string operation on various types. In JS you can append text and types. In Hyperscript that’s "equal" to put.

**Comment by iamjameswalters** [comment]
Sure. In that case, the [make documentation](https://hyperscript.org/commands/make/) needs to be updated, because the code example shows using `make` to create a `<span class="toppings">` and `append`ing it to the element `#toppings`. It doesn't much matter to me which way the keyword works in the language, it matters that the code in the docs doesn't work, so either the language needs to be fixed to make the code work, or the code in the docs needs to be changed to fit the language implementation.

**Comment by chilljalapeno** [comment]
Hi, was wondering if this is fixed or not, because it does not work for me and I want to know if I am doing something wrong or if this issue still persists

**Comment by 1cg** [comment]
I come bearing glad tidings: I have fixed this bug in `append`
