### ISSUE TITLE
[Bug] "x is a String" is true if x is undefined

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#409]
```
  set x to undefined
  log (x is a String)
```

will log `true` rather than false which is definitely wrong

**Comment by hudon** [comment]
`x is a Number` will also output "true", fwiw

**Comment by dz4k** [comment]
https://github.com/bigskysoftware/_hyperscript/blob/1622876121f5e92c74ddba7b9a28062323a0df5f/src/_hyperscript.js#L1925

If the value is loosely equal to null, all type checks return true.

https://github.com/bigskysoftware/_hyperscript/blob/1622876121f5e92c74ddba7b9a28062323a0df5f/src/_hyperscript.js#L3745

Looks like you can avoid this by using `is a String!` @1cg is this documented? I couldn't find it
