### ISSUE TITLE
[Bug] Handlers are lost when HTML is replaced 

### ISSUE THREAD

**Issue by davidalejandroaguilar** [bigskysoftware/_hyperscript#421]
# Problem

Whenever some HTML is replaced (for example by Turbo, whether it's a Drive restoration visit or a Turbo Frame being replaced), Hyperscript's handlers are lost, needing to reload the page.

This can be easily reproduced by going to the Playground, loading the Go To Button example and then running this in the console:

```js
const element = document.getElementById("contents")
const html = element.outerHTML
element.outerHTML = html
```

# Expected behavior

I expected behaviors to be automatically attached again. 

---

Maybe this can be accomplished via event delegation or observers?

**Comment by davidalejandroaguilar** [comment]
[Here's a new Rails app](https://github.com/davidalejandroaguilar/hyperscript-bug) reproducing the issue. [Here's the relevant commit](https://github.com/davidalejandroaguilar/hyperscript-bug/commit/6cc01e9eb1c5920555ee4fe3bc297769621701e1).

The repo also shows the Alpine.js version, which does work (except for `x-bind:class` on Turbo Drive restoration visit, for which I opened an issue [here](https://github.com/alpinejs/alpine/discussions/3485)).

Here's a video reproducing the issue too. 

https://user-images.githubusercontent.com/15317732/227667850-492b0d1e-27e1-4533-b2d2-ce0a1403ff55.mov

**Comment by dz4k** [comment]
Alpine uses a MutationObserver to detect new elements. _hyperscript does not. When new elements are added, call `_hyperscript.processNode(/* those elements */)` to activate _hyperscript code.

@1cg should we use a mutation observer to automatically call processNode? I think this was talked about before but I don't remember if any conclusion was reached

**Comment by davidalejandroaguilar** [comment]
Glad there's a quick workaround for Turbo with:

```js
document.addEventListener("turbo:render", (event) => {
  _hyperscript.processNode(event.target);
});
```

---

Yeah I figured the lack of a mutation observer was the culprit. That sounds like the best approach. Let me know how I can help. I'm not familiar with the repo but if you need a hand feel free to point me in the right direction.

**Comment by 1cg** [comment]
I have shied away from a Mutation Observer for performance reasons.  I'm willing to revisit it at some point, but I don't have a lot of bandwidth to look at it now unfortunately.
