### ISSUE TITLE
Enable hyperscript for dynamically created elements 

### ISSUE THREAD

**Issue by BoPeng** [bigskysoftware/_hyperscript#432]
I am creating a dynamic table with new rows inserted in javascript. The HTML code is similar to the following with a button in the last column having a hyscript attribute.

```html
<template>
    <tr>
        <th>
        </th>
        <td>
            <a class="mx-2"
                _="on click remove closest tr">remove</span>
            </a>
        </td>
    </tr>
</template>
```

The problem is that when the template is cloned and inserted to a table, the `_=""` code does not work. Is there anyway for me to activate hyperscript for the element? I suppose I am looking for something like

```javascript
// create element by cloning template
element.getElementByTagName('a').ENABLE_HYPERSCIPT
// insert element to the table
```

**Comment by BoPeng** [comment]
On a related bug, even in the cases when hyperscript is enabled,

```html
    <tr>
        <th>
        </th>
        <td>
            <a class="mx-2"
                _="on click remove closest tr">remove</span>
            </a>
        </td>
    </tr>
```

failed to work and I have to use

```html
    <tr class="tablerow">
        <th>
        </th>
        <td>
            <a class="mx-2"
                _="on click remove closest .tablerow">remove</span>
            </a>
        </td>
    </tr>
```

I am not sure why the former did not work.

**Comment by dz4k** [comment]
The correct syntax is `remove closest <tr />`, note the angle brackets.

**Comment by bioworkflows** [comment]
Thanks. I learned the syntax from https://hyperscript.org/expressions/closest/ where `closest div` is given as an example. Should the `div` be `<div />` as well?

**Comment by dz4k** [comment]
Yes, sorry about that.

Would you like to open a PR to fix it -- no worries if not?

**Comment by bioworkflows** [comment]
I can create a PR. Do you have any idea about the original question, namely enabling hyperscript on the dynamically cloned elements?

**Comment by dz4k** [comment]
Oh yeah, call _hyperscript.processNode with the newly created element.

**Comment by bioworkflows** [comment]
Thanks. PR created.

**Comment by bioworkflows** [comment]
I can also confirm that calling `_hyperscript.processNode` works. Thanks!
