### ISSUE TITLE
Double result when fetching an API

### ISSUE THREAD

**Issue by SaschaValentin** [bigskysoftware/_hyperscript#439]
Running this
```
<div _="on load fetch 'https://jsonplaceholder.typicode.com/posts' as Object
           set $test to result        
           log it
           end">
```
in Hyperscript will lead to two same arrays:
![grafik](https://github.com/bigskysoftware/_hyperscript/assets/48714823/70390903-b211-4cb1-a73f-f0fcb87c5c32)

But when I `console.log($test)` in browsers console, there is only one array. Is this an known issue?

The problem is when I´m looping over $test everything appears two times.

**Comment by 1cg** [comment]
iirc we looked into this on the discord and settled on it not being an issue, correct?
