### ISSUE TITLE
Where is the "Whole 9 Yards" version?

### ISSUE THREAD

**Issue by SaschaValentin** [bigskysoftware/_hyperscript#442]
The docs say hyperscript_w9y.js file could be downloaded from the dist directory. But there is no such file. For former versions of hyperscript this was true. Maybe the functions are now incorporated in the _hyperscript.js or do we need to reference socket and worker each individually?

**Comment by jhches21** [comment]
Somewhat related.

The w9y works with commands "render" while the 0.9.11 doesn't. Took me long time to figure this out.



At end I decided to download the w9y from the playground.

**Comment by nicola-gigante** [comment]
Any news on where is this version officially located?

I've downloaded it from [https://hyperscript.org/js/_hyperscript_w9y.min.js](https://hyperscript.org/js/_hyperscript_w9y.min.js) and it works but this seems quite weird...

**Comment by 1cg** [comment]
Yeah, we deprecated this but missed a reference in the docs, sorry about that.
