### ISSUE TITLE
Passing context (such as 'target', and 'event) into functions

### ISSUE THREAD

**Issue by aboisvert** [bigskysoftware/_hyperscript#446]
Hi, this is either a question or an issue depending on whether this is a supported feature :)

I'd like to pass some of the invocation context into functions, as follows:

```js
  on every mousemove
    mouseMoveHandler(target, event)
  end
```

The issue is that both `target` and `event` are null when passed as arguments to my `mouseMoveHandler`.  (They are not null inside the `on` block, as evidenced by a local `log` statement)

Is this meant to be supported?

**Comment by QINGCHARLES** [comment]
This works for me:
`		<input asp-for="StreetAddress" autocomplete="off" placeholder="e.g. 4128 N Tripp Ave" _="on keyup call fetchSuggestions(event.target.value)" />
`
'
	<script type="text/hyperscript">
		def fetchSuggestions(query)
alert(query)
		end
	</script>
'
But if I put anything more complicated in the function I get errors 🙄

**Comment by raysuelzer** [comment]
Okay, but how do we just call a javascript function we have? I get the following error: 

Cannot read properties of undefined (reading 'key')

**Comment by 1cg** [comment]
Just tested this locally and it works now
