### ISSUE TITLE
Combine target selector with expressions => Cannot take a property of a non-symbol: queryRef

### ISSUE THREAD

**Issue by rdehuyss** [bigskysoftware/_hyperscript#452]
Hi,

First of all - who needs chatGPT when you can use HyperScript which reads like English 🎉. Thanks so much for this great piece of art.

I'm trying to use hyperscript to select the active tab and I was hoping to use the following:
```html
<ul hx-ext="class-tools"  _="on click remove .is-active from the children of me then add .is-active to closest <li/> of target">
  <li><a>Tab 1</a></li>
  <li><a>Tab 2</a></li>
  <li><a>Tab 3</a></li>
</ul>
```

I also tried:
`on click remove .is-active from the children of me then add .is-active to closest parent <li/> of target`

I get the following exception however:
`Cannot take a property of a non-symbol: queryRef`

Am I doing something wrong?

**Comment by 1cg** [comment]
hey ronald, sorry this sat so long next time please just email me!

just for the record, it's a small error: you want `to` instead of `of`:

```applescript
on click 
  remove .is-active from the children of me then 
  add .is-active to closest <li/> to target
```

https://codepen.io/1cg/pen/yyBgmKL?editors=1001

**Comment by 1cg** [comment]
I should also note you can use the `take` command for this:

```applescript
on click 
  take .is-active from my children for the closest <li/> to target
```
