### ISSUE TITLE
Astrojs impossible to use _hyperscript.d.ts is not a module

### ISSUE THREAD

**Issue by FDiskas** [bigskysoftware/_hyperscript#463]
It is impossible to use with Astrojs because - by default Astro uses typescript. In your case typescript is unsupported.
![image](https://github.com/bigskysoftware/_hyperscript/assets/468006/3ced7cee-db16-409d-973b-2864ccd882ee)

```
File '***/node_modules/hyperscript.org/src/_hyperscript.d.ts' is not a module.ts(2306)
```

related #456

**Comment by FDiskas** [comment]
what is `HyperscriptObject` ?
![image](https://github.com/bigskysoftware/_hyperscript/assets/468006/88c60357-a420-4036-be42-f6973c851408)

**Comment by 1cg** [comment]
fix is coming in next release, sorry for the issue
