### ISSUE TITLE
Go command offset feature does not work

### ISSUE THREAD

**Issue by balazskosi** [bigskysoftware/_hyperscript#464]
When adding the offset part to a go command it ceases to work, only flickers in place.

```hyperscript
on click go to the top of #bar -30px
```

Hyperscript version: 0.9.7

This works: https://tinyurl.com/go-without-offset
But if you add -30px at line 12, it doesn't: https://tinyurl.com/go-with-offset

**Comment by 1cg** [comment]
we have a fix for this coming in the next release.  Sorry for the issue.
