### ISSUE TITLE
access cookie / localStorage

### ISSUE THREAD

**Issue by Zerotask** [bigskysoftware/_hyperscript#466]
I want to show a modal the first time a user logs in. Therefore I have a state in a cookie or localStorage, e. g. modalOpen which can either be missing or true and in these cases the modal should be shown. Afterwards it should set/update the cookie/localStorage, e. g. showModal=false

The specific action could be to add a css class (e. g. modal-open) or call an onclick modalId.showModal() (daisyUI)

**Comment by dz4k** [comment]
You can access localStorage as follows:

```applescript
get localStorage.modalOpen
-- do stuff
set localStorage.modalOpen to value
```

**Comment by leandergangso** [comment]
this saved me :)
looks like this is not mentioned anywhere in the [docs](https://hyperscript.org/reference).

**Comment by 1cg** [comment]
that's the standard localStorage API so we don't have it documented

we do have documentation for cookies though:

https://hyperscript.org/expressions/cookies/
