### ISSUE TITLE
Can hyperscript listen to HX-Trigger Header events?

### ISSUE THREAD

**Issue by AxelRHD** [bigskysoftware/_hyperscript#477]
I would like to render a popup notification (with notie js) on en event triggered by the HX-Trigger header of htmx.

Is this possible? Or what is the best solution to render such messages?

Thanks.

**Comment by AxelRHD** [comment]
Simple example without the use of a library:

```html
<div div class="notifier is-hidden" hidden
    _="on notieLoginSuccess from body
      alert('login success')"
></div>
```

This element is settled directly in body.

**Comment by 1cg** [comment]
Yep, hyperscript can listen for HX-Trigger triggered events, they are just normal events.
