### ISSUE TITLE
Include exclamation mark character in class expressions

### ISSUE THREAD

**Issue by adicco** [bigskysoftware/_hyperscript#482]
It would be neat if one could use Tailwind's [important modifiers](https://tailwindcss.com/docs/configuration#important-modifier) (basically prefixing class names with `!`). Presently:

```
 _="on click toggle .!hidden on <.reason-block/> in the closest parent <.item-block/>"
```

will raise:

```
Expected either a class reference or attribute expression

on click toggle .!hidden on <.reason-block/> in the closest parent <.item-block/>
                ^^

 Error: Expected either a class reference or attribute expression

on click toggle .!hidden on <.reason-block/> in the closest parent <.item-block/>
```

**Comment by andryyy** [comment]
Hum. Or could be added here https://github.com/bigskysoftware/_hyperscript/blob/b5720199536031a5748e35020c20141d1d6fc02c/src/_hyperscript.js#L250 but it shouldn’t. 

It’s not valid syntax. It may contain \! but I’m not sure if it’s valid as first character. The queryselector may not like it. 

It’s a good addition to https://github.com/bigskysoftware/_hyperscript/pull/299/files. A possible way could be to parse @class as an array of strings and match against the needle. Sounds slow just reading it.

**Comment by adicco** [comment]
For the record I managed to do what I wanted using `between`:

```on click toggle between .hidden and .flex on <.reason-block/> in the closest parent <.item-block/>```

But there might be other cases where supporting the `!` is legitimate

**Comment by dz4k** [comment]
You can use the class expression syntax: 

    toggle .{"!hidden"}

**Comment by dz4k** [comment]
You can use the class expression syntax: 

    toggle .{"!hidden"}

**Comment by adicco** [comment]
This works, thank you @dz4k
