### ISSUE TITLE
Name conflict with established project

### ISSUE THREAD

**Issue by snowbldr** [bigskysoftware/_hyperscript#484]
There's a decade old project hyperscript, https://github.com/hyperhype/hyperscript

Kinda sucks this project is crushing that one in SEO.

That is all.

**Comment by 1cg** [comment]
yep, found that out after I had secured https://hyperscript.org

originally tried to call this hypescript, but npm would let me

my understanding is that that project has been supplanted by stuff like JSX, etc for most web developers today
