### ISSUE TITLE
control over repeat timer

### ISSUE THREAD

**Issue by baseplate-admin** [bigskysoftware/_hyperscript#489]
Hi,

I have a complex requirement that requires me to restart the timer.

```hyperscript
on init 
   repeat forever
        wait 10s
        js
            call_function()
        end
```

So i what i want is 

```typescript
function call_function(){

       // do something
       restart the wait 

}

```

with something like
```html
<button onclick='call_function()'>This button can also call the function</button>
```

**Comment by andryyy** [comment]
You should be able to use `wait for a eventName or 10s`. After that line add `if the result is 'eventName' continue end`. Otherwise the loop completes and calls your function. 

Only quote the event name when comparing it against the result.

**Comment by baseplate-admin** [comment]
I will have a look. thanks for fast response

**Comment by andryyy** [comment]
I added the click event to my response and a reference to the button. :)
