### ISSUE TITLE
Pattern Matching - is it possible to support something like when param1 and param2 is like 'abc*' and 'xyz*'

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/_hyperscript#5]
Is it possible to add pattern matching and switch-like statement? To make it more natural it can be like:

```
when param1 and param2 is like 'abc*' and 'xyz*' ... when param3 is ...
```

**Comment by chg20** [comment]
Thank you for your feedback!  

Yes, I am planning on buffing out the language extensively over the next year, but it will be slower than I would like.  :)

Next up are functions and getting the asynchronous model worked out.  Pattern matching should be pretty easy once that is in.

Thank you for your interest in the project!

**Comment by 1cg** [comment]
You can now do matching against dom selectors.  We will eventually support regular expressions as in javascript
