### ISSUE TITLE
"If" functionality which remove/add element from the DOM

### ISSUE THREAD

**Issue by matndev** [bigskysoftware/_hyperscript#504]
I would like to replicate the ngIf directive from Angular in hyperscript.

To do that I need to remove or add from DOM elements based on a condition.

But I didn't find a manner with hyperscript currently.

Here an example code to begin with : 

```html
<div _="set global currentItem to 0">

        <div **for loop with index **>
            <div class="element**index**"">
                <p>Hello world</p>
            </div>
        </div>

        <button _="on click show :currentItem and remove others then halt the event">
</div>
```

The idea is to hide/show (by removing or adding) element depending its index. If the index is equal tu currentItem it shows the element otherwise it is removing it.

**Comment by 1cg** [comment]
The `show` command supports a `when` clause:

```applescript
   show <div/> in #parent-div where its id equals :currentItem
```

that will show the div with the given id and hide the others
