### ISSUE TITLE
[QUESTION] 1.0 Release

### ISSUE THREAD

**Issue by danielnieto** [bigskysoftware/_hyperscript#515]
I see that the language is pretty complete now, and I'm loving it so far, but when is 1.0 planned to be released? I can see references to it since 2 years ago and last release was 4 months ago, just curios, is there a roadmap or release schedule?

**Comment by minhquana3** [comment]
I'm impressed with this tool and eager to see the full release of version 1.0. I wonder what's on their roadmap. I think they are focusing their resources in htmx. However, this tool is so much better than writing JavaScript. :)

**Comment by 1cg** [comment]
hoping to have hyperscript at 1.0 in Q1 of 2025
