### ISSUE TITLE
docs for `wait` command include invalid syntax

### ISSUE THREAD

**Issue by CharlesTaylor7** [bigskysoftware/_hyperscript#517]
### Problem

The documentation for the `wait` command advertises syntax that doesn't actually parse. 

On this page of the docs:
https://hyperscript.org/commands/wait/#description

This snippet:
```
wait for load or 1s
if the result is not an Event
  throw 'Took too long to load.'
end
```

### Workaround

The comparison `the result is not an Event`, fails to parse, but replacing the `an` with an `a` makes it hunky dory. 

### Potential Fix

Either we can (1) update the docs, or (2) update the parser to allow the construct of `is not an Event`. 
I personally favor extending the parser to make this work.

### Error

<img width="591" alt="Screen Shot 2024-02-09 at 6 45 14 PM" src="https://github.com/bigskysoftware/_hyperscript/assets/16541866/134fffdb-a2a6-4027-91cb-4b6fd7cef81f">

Stacktrace:
```
    at a.raiseParseError (http://unpkg.com/hyperscript.org@0.9.12:1:12649)
    at i.raiseError (http://unpkg.com/hyperscript.org@0.9.12:1:6620)
    at i.requireToken (http://unpkg.com/hyperscript.org@0.9.12:1:7520)
    at http://unpkg.com/hyperscript.org@0.9.12:1:71097
 ```

**Comment by kakuche** [comment]
I had a similar issue were the syntax
`wait for <event> from <source> or <time expression>` did not work, changing the order of the commands to
`wait for <event> or <time expression> from <source>` fixed it for me.
I don't know if this would be considered a bug or just the documentation being misleading.

**Comment by SennaSanzo** [comment]
I haven't had the time to look into that in detail for now but if this is working, this is good ! I'll come back if it fixes my issue. Thank you so much!
