### ISSUE TITLE
Array.sort(compareFn) Not Working in Some Browsers

### ISSUE THREAD

**Issue by robertology** [bigskysoftware/_hyperscript#519]
Looks like Chromium based browsers (but not Safari) do not handle the callback function given to `array.sort()`.

This was discovered from
https://codepen.io/htmx/pen/BamPGPE?editors=1101

Note: `sort()` without the callback function works as expected.

`<button _="on click set x to [5, 9, 1] then log x.sort(\ a, b -> a > b)">Test</button>`

Expected result: `[1,5,9]`

Actual results (on MacOS 14.3.1):

✅ Firefox 122.0.1: `[1,5,9]`
✅ Safari 17.3.1: `[1,5,9]`
❌ Chrome 120.0.6099.216: `[5,9,1]`
❌ Chrome 121.0.6167.184: `[5,9,1]`
❌ Brave 1.62.165 Chromium: 121.0.6167.184: `[5,9,1]`

**Comment by KDreynolds** [comment]
I can look into this.

**Comment by 1cg** [comment]
believe it or not that's not a hyperscript issue, it's a javascript issue, the correct comparison function is `a - b`, see:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
