### ISSUE TITLE
Feature: Implement SSE

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#52]
From discord: 

```
server sse://whatever
    on foo
          -- additional commands.  "it" is populated with the event?
    end

    on message
        -- more commands
    end

on unhandled
```

**Comment by benpate** [comment]
I've made some updates to this that are (nearly) ready for testing.  I want to add public `connect()` and `close()` methods to the variable that's published into the hyperscript scope, and then I think this will be ready to go.

@1cg -- There's one experimental change that I wanted to get your eyes on before I move forward:

I'm using [JSDoc-formatted comments](https://jsdoc.app) in most of the new EventSource code.  JSDoc works with the Typescript validator to provide fantastic insights and code validation if your set up your dev environment to use it.  Otherwise, they're just specially formatted comments, so they are non-intrusive and don't require a build step or a compiler.  You can run the raw code without any modifications.  

What do you think?  If this works for you, I'll take a pass at adding JSDoc comments in a separate PR.  Like unit tests, the benefits grow exponentially as more code is covered :)

**Comment by benpate** [comment]
Another issue I'm having trouble with is parsing event names correctly.  A regular, mixed case string seems to work fine.  But if I include a number, or a dash `-` or a colon `:` then the parsing breaks.  I think I'm probably using the wrong function to identify the event name.  What is a better choice instead of `parser.requireElement("dotOrColonPath"...)`?

**Comment by 1cg** [comment]
parser.requireElement("stringLike") is more flexible, it will allow you to take either a string or a naked string, which is white space terminated.
