### ISSUE TITLE
Other attribute names don't register

### ISSUE THREAD

**Issue by ethanthoma** [bigskysoftware/_hyperscript#520]
Hello,

I am currently using reasonml and tyxml. However, tyxml doesn't support attribute names that with `_` in them.  To solve this I tried:
- Using `data-hs` and `hs` as indicated in the README.md but those don't work. 
- Registering the elements using `_hyperscript.processNode` but that only works for `_` and not for `data-hs` or `hs`.

Maybe I am confused about what the README.md implies. Thanks.

**Comment by cemerick** [comment]
This should settle things for you:

```
    <meta name="htmx-config" content="{"attributes":"hs"}" />
```

With that in place (positioned before you load hyperscript.js IIRC), you can use tyxml's underscore-prefixed attributes to emit `hs` attrs that will get picked up.

**Comment by ethanthoma** [comment]
Thank you, I will try that!

**Comment by ethanthoma** [comment]
It worked. Thanks again. I was regexing hs into _ in the meantime so this should make it a smidge faster lol
