### ISSUE TITLE
How to set JS object property using hyperscript?

### ISSUE THREAD

**Issue by oleg-mitnik-dev** [bigskysoftware/_hyperscript#532]
For example, to mute video in JavaScript we can do
```
const video = document.getElementById("myVideo");
video.muted = true;
```

To get access to a video in hyperscript we can use `#myVideo`.
Then we can `call #myVideo.play()` or `call #myVideo.pause()` functions . It's ok.

But how to set `video.muted` to true|false|toggle **in hyperscript** ?

**Comment by andryyy** [comment]
Pretty sure you can use `set #myVideo.muted to true`. 

I’m on a spinner right now, can’t test.

**Comment by oleg-mitnik-dev** [comment]
> Pretty sure you can use `set #myVideo.muted to true`.
> 
> I’m on a spinner right now, can’t test.

Awesome! It works 👍

**Comment by dz4k** [comment]
For future readers of this issue:

All of these work to access and set properties:

```
#myVideo.muted
#myVideo's muted
muted of #myVideo
```
