### ISSUE TITLE
How can I remove an event listener?

### ISSUE THREAD

**Issue by minhquana3** [bigskysoftware/_hyperscript#534]
Is there a way to remove the event listener? Here is my code. 

`<input id="email" name="email" class="input" type="email" placeholder="Input email" value={ contact.Email } _="on focus remove the next <ul/> then append "<p></p>" to the closest parent <div/>" hx-get="/contacts/validate/email" hx-target="next .help" hx-swap="outerHTML" hx-push-url="false"/>`

When user FIRST clicks on the input field, it will remove the `<ul>` element. However, after this event, I want to remove this event listener. This means that `_="on focus..."` will not run after the first time. 

How can I achieve this with hyperscript?

**Comment by twaite** [comment]
Could you put the event listener on the `<ul />` instead so that the listener is removed along with that element?

```html
<input
  id="email"
  name="email"
  class="input"
  type="email"
  placeholder="Input email"
  value={ contact.Email }
  hx-get="/contacts/validate/email"
  hx-target="next .help"
  hx-swap="outerHTML"
  hx-push-url="false"
  _="on focus append '<p></p>' to the closest parent <div/>"
/>
<ul _="on focus from input remove me">
   <!-- ... -->
</ul>
```

**Comment by minhquana3** [comment]
This works perfectly. Thank you so much.

**Comment by minhquana3** [comment]
This works perfectly. Thank you so much.
