### ISSUE TITLE
custom event triggering isn't picked up by hyperscript

### ISSUE THREAD

**Issue by muhammadismailkhan0009** [bigskysoftware/_hyperscript#536]
I am trying to change value of a tag using hyperscript by creating custom event(dataAssigned). 
but when webpage is fully loaded, the event trigger isn't being reflected on element.

Here is the [live demo on jfiddle](https://jsfiddle.net/d7t31b92/13/)

for reference, here is the code:
```
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>apiTrove text chat</title>
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
  </head>

  <body>
    <p _="on dataAssigned call alert('You clicked me!')">Not Found. Try Again</p>
    
    <p _="on load call alert('Button is clicked')"> </p>
    
    
    <button id="connectBtn" onclick="processData()">Connect
    </button>

    <script>
      
      function processData() {

        const dataAssignedEvent = new CustomEvent('dataAssigned', {
          bubbles: true,
          detail: {
            senderId: '123'
          }
        });
        document.dispatchEvent(dataAssignedEvent);
      }

    </script>

    <script>
      document.addEventListener('dataAssigned', (event) => {
        
        console.log('dataAssigned event was triggered');
      });

    </script>
  </body>

</html>
```

kindly help me understand why is it not working?
or is it that hyperscript doesn't support such behaviour(reactive behaviour where it keeps listening to events triggers irrespective of tag and position?)
thank you

**Comment by WedersonCD** [comment]
Hello, it isn't working because the event is being sent to 'document' and the 'on event' listen their own tag.

You can add 'from document' to filter the event target, as bellow:

`<p _="on dataAssigned from document call alert('You clicked me!') end">Not Found. Try Again</p>`

**Comment by muhammadismailkhan0009** [comment]
@WedersonCD i have used your suggestion and have verified that it works. thank you :)
on sidenote, it'd be better if this point in included in official docs so that it doesn't cause problem for future.
if needed, i can create a PR for it.
