### ISSUE TITLE
[Doc improvment] Add a example for set value for a input element.

### ISSUE THREAD

**Issue by zw963** [bigskysoftware/_hyperscript#538]
Consider we are use so many input element together with `hx-include` when use htmx, there is no a example for this is strange.

I spend some times to figure this out, following is a example: (use 

```html
<input type="hidden" name="value1" value="">
<span></span>
<tc-range-slider 
min="0"
max="100"
value1="10"
value2="90"
round="0"
script="on change put my.value1 into the previous <span/>
then put my.value2 into the next <span/>
then set (previous <input/>).value to my.value1
then set (next <input/>).value to my.value2
"
<input type="hidden" name="value2" value="">
<span></span>
>
```

The usage of `set (previus <input/>).value` is missing in the document.

Do you consider add a example like that?

--------------------------

One more question here, can we simplify above script a bit?

because we set same `my.value1` to both input tag and span tag, so i am wonder if we can use like this:

```
on change set (previous <input/>).value and (previous <span/>).innerHTML to my.value1
```

But it not work, because `and` keyword used in the `if` expression, it not work here, any alternative?

Thanks

**Comment by zw963** [comment]
Does anyone still maintain this project?

**Comment by 1cg** [comment]
hi there

```applescript
then set (previous <input/>).value to my.value1
```
can be written as
```applescript
   set the value of the previous <input/> to my value1
```
the `of` property reference is for handling binding issues like you have here more gracefully by moving the property to the front

and yes, this project is maintained, i've been busy with htmx and classes but i'm hoping to get to 1.0 in Q1 of 2025
