### ISSUE TITLE
Feature Request: stop/start commands

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#54]
I stumbled into this while working on SSE Support (#52).  I've now exposed functions like `call MyConnection.start()` and `call MyConnection.stop()` to the rest of hyperscript.  This works fine, but it would be better if I could say something like`start MyConnection` and `stop MyConnection` instead.

We have now added several kinds of background services: [Workers](https://hyperscript.org/features/worker/), [WebSockets](https://github.com/bigskysoftware/_hyperscript/blob/dev/src/lib/socket.js), and [SSE](https://github.com/benpate/_hyperscript/blob/pr-sse/src/lib/eventsource.js) that could all use this kind of syntax.  And it seems likely there could be others in the future that could implement this, too.

**Interfaces**
I think it could be implemented using something like a [duck-typed interface](https://en.wikipedia.org/wiki/Duck_typing), so the `start` keyword would take a single argument -- the name of the object in the hyperscript context -- and try to call the `.start()` method on that object.  If the method doesn't exist, then hyperscript could log an error.  

The `stop` keyword would do the same thing, searching for a `.stop()` method instead.

**Naming**
These names are not set in stone -- there are many other pairs that might work instead (connect/disconnect, open/close, etc) -- but these seem like the most generic terms that would be applicable in the widest range of circumstances.

**Comment by 1cg** [comment]
we are going to support general top level method invocation

```
  stop() MyConnection
  stop() the connection
```
etc, rather than adding a ton of new commands
