### ISSUE TITLE
Dynamic ID doesn't work with template strings

### ISSUE THREAD

**Issue by tvandinther** [bigskysoftware/_hyperscript#540]
I am trying to use a template string to make a dynamic reference to an ID. Unfortunately this doesn't work due to an unterminated string error. Here is a [jsfiddle](https://jsfiddle.net/uzbxnf08/11/) with an example and a workaround (using an intermediate variable).

My expectation is for any expression to be valid for use as a dynamic ID. Is this a bug or is this intended? If intended, what is the reasoning for the limitation?

---

```html
<button id="foo" _="on click toggle [@hidden] on #{`test-${event's target.id}`}">
  Show/Hide
</button>
<div id="test-foo">
  Hello
</div>

<button id="bar" _="on click set id to `test-${event's target.id}` toggle [@hidden] on #{id}">
  Show/Hide
</button>
<div id="test-bar">
  Hello
</div>
```

**Comment by 1cg** [comment]
yeah it's a bug in the tokenizer, but fixing it would be _really_ ugly

for this you could say:

```applescript
on click
  set idToToggle to `test-${the event's target's id}` 
  toggle [@hidden] on #{idToToggle}
```

as a workaround.  Sorry about that.
