### ISSUE TITLE
how to uncheck a radio

### ISSUE THREAD

**Issue by glfeng318** [bigskysoftware/_hyperscript#546]
```<input type="radio" name="expand" _="on click halt the event remove [@checked] on me" class="ml-4">```
not work as expected.
And how to toggle `@checked` attribute of a radio?

**Comment by Nicero** [comment]
Simply remove `[` and `]`:

`_="on click remove @checked"`

What behaviour should have a toggle radio button?

`_="on click if me match <:checked/> ..."`
`_="on click if me match <:not(:checked)/> ..."`
