### ISSUE TITLE
"pick match" with RegEx flag does not seem to work

### ISSUE THREAD

**Issue by djeastm** [bigskysoftware/_hyperscript#549]
When I attempt to use the example in the documentation for the 'pick match' command (https://hyperscript.org/commands/pick/#pick-match), I get a syntax error

This is the example code:
```applescript
set str to "The quick brown fox jumps over the lazy dog."
pick match of "the (\w+)" | i from str
```

And the error
![image](https://github.com/bigskysoftware/_hyperscript/assets/5298428/830ffa4a-6e02-47c8-a548-bdaf47509ced)

This part of the source (line 5944) seems to be where there might be an issue:

```javascript
if (tokens.matchOpToken("|")) {
    flags = tokens.requireToken("identifier").value;
}
```

I also noticed there was no test of the RegEx flag in `/test/command/pick.js`

**Comment by 1cg** [comment]
added a test for it, appears to be working in the `dev` branch at least
