### ISSUE TITLE
Feature Request: `toggle between` syntax for elements

### ISSUE THREAD

**Issue by mekhami** [bigskysoftware/_hyperscript#55]
Basically:
```
<a _="on click toggle between .this-class and .that-class on #my-element">Click</a>
<div id="my-element" class="this-class">
```

When you click the `<a>`, it should remove `this-class` and add `that-class`, or vice versa, depending on the initial state.

Alternative syntax, maybe: `on click toggle between .this-class, .that-class on #my-element` but I think the 'and' works better here.

Very helpful for a broad range of UX patterns.

**Comment by 1cg** [comment]
this works in dev
