### ISSUE TITLE
how can i use the 'new' operator for a variable?

### ISSUE THREAD

**Issue by javiermartinez27** [bigskysoftware/_hyperscript#551]
I'm trying to set a variable to a date, this is what i'm currently doing

`_="init set startTime to Date('01/01/2024') then log startTime"></p>`

The problem is, this just gives me the current date, because for it to work, it needs to be `new Date('01/01/2024')`. So, how could i make it work?

**Comment by WedersonCD** [comment]
<p _="init js() return new Date('01/01/2024') end log the result"></p>

**Comment by javiermartinez27** [comment]
thank you!
