### ISSUE TITLE
Appending to a table removes the events of its childrens

### ISSUE THREAD

**Issue by ignamartinoli** [bigskysoftware/_hyperscript#555]
With this dynamic table example:

```html
<table>
	<thead>
		<tr>
			<th>Column 1</th>
			<th>Column 2</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody id="table">
		<tr>
			<td><input type="text" /></td>
			<td><input type="text" /></td>
			<td><button _="on click remove closest <tr />">Remove</button></td>
		</tr>
	</tbody>
</table>
<button _="on click append `
	<tr>
		<td><input type='text' /></td>
		<td><input type='text' /></td>
		<td><button _='on click remove closest <tr />'>Remove</button></td>
	</tr>
` to #table">Add row</button>
```

The `on click remove closest <tr />` handler works, until a row is added. Then only the `append` command will work, but disabling the `remove` command.

**Comment by 1cg** [comment]
fixed with https://github.com/bigskysoftware/_hyperscript/commit/3fb0888fb6cbde77db7a6653d222dea51436add3

**Comment by ignamartinoli** [comment]
Hi. I tried the snippet again, and it didn't work as expected

**Comment by namzug16** [comment]
@ignamartinoli  The fix has been merged but it has not been released yet, I'd recommend you to put the _hyperscript.js file with the fix directly in your project until the release of the new version

**Comment by ignamartinoli** [comment]
@namzug16 thanks, I didn't realize the fix wasn't in the release.

Really glad the project revived. It looks really promising
