### ISSUE TITLE
Calling hyperscript functions from javascript

### ISSUE THREAD

**Issue by rauwebieten** [bigskysoftware/_hyperscript#556]
Following the guide on https://hyperscript.org/docs/#functions

This does not seem to work:
Uncaught ReferenceError: waitAndReturn is not defined

https://jsfiddle.net/rauwebieten2/mrhfktgd/1/

**Comment by 1cg** [comment]
this is a timing issue: the javascript executes before the hyperscript does, if you put the call on a button event handler and click it you'll see it works.  Not a ton we can do about that unfortunately.
