### ISSUE TITLE
toggling @disabled on the next select actually toggles it on its children options

### ISSUE THREAD

**Issue by 8549** [bigskysoftware/_hyperscript#558]
Code to reproduce (tested in playground):
```html
<form action="/add" method="post" autocomplete="off">
  <input type="checkbox" name="have_p" _="on change toggle @disabled on the next <select/>" />
  <select name="p_format" required>
    <option value="a">A</option>
    <option value="b">B</option>
  </select>
</form>
```
Issue persists even by addressing the select with an id or by targeting `the parentElement of the next <option/>`.

**Comment by 8549** [comment]
I debugged the script execution and found that the culprit is in the implementation of Runtime.forEach()
https://github.com/bigskysoftware/_hyperscript/blob/1e65fb101e2953f680ce958f7de31c266356ad87/src/_hyperscript.js#L1530-L1544
 the HTMLSelectElement which is passed as value is considered an iterable so the wrong else-if branch is executed (and the toggle command is executed on the select's iterables -- its children options!) instead of the default (call once func on value).
![immagine](https://github.com/user-attachments/assets/03f5478d-fcb7-4db1-a20a-8cbba762962c)

**Comment by sanchawebo** [comment]
I currently have the same problem. Did you happen to find a workaround for this?

**Comment by 8549** [comment]
@sanchawebo The dev confirmed that he's going to fix this issue in September:
![immagine](https://github.com/user-attachments/assets/5be97b74-c16a-4681-add2-6715f2389750)

**Comment by 1cg** [comment]
this is fixed now https://github.com/bigskysoftware/_hyperscript/commit/3884fbad117ae98d68733217b00c55f909e2a678
