### ISSUE TITLE
[shadowDOM] hyperscript does not find elements outside the shadowRoot

### ISSUE THREAD

**Issue by rolandoam** [bigskysoftware/_hyperscript#559]
suppose you have a very simple button trying to open a modal:

```html
<button _="on click call #my-modal.show()">open</button>
```

If this button is in a regular DOM tree, it will work just fine. However, if the button is inside the tree of a shadowDOM object, then it complains that `#my-modal` is nil.

Example lit component:

```ts
import {LitElement, css, html} from 'lit';
import {customElement} from 'lit/decorators.js';
import _hs from 'hyperscript.org';
import * as htmx from 'htmx.org/dist/htmx';

@customElement('test-element')
export class TestElement extends LitElement {
  // make hs & htmx aware of elements in this shadowRoot
  firstUpdated() {
    if (this.shadowRoot) {
      const children = Array.from(this.shadowRoot.children);
      children.forEach(e => {
        _hs.processNode(e);
        htmx.process(e);
      });
    }
  }

  render() {
    return html`
      <button _="on click call #my-modal.show()"></button>
    `;
  }
}
```

If I change the hs code by a regular js call (e.g. `onclick="document.querySelector('#my-modal-show').show()"`), all works just fine. I think the problem is that the querySelector might be scoped to the shadowRoot somehow, because if I put the modal inside the component, it also works.

**Comment by aearly** [comment]
I have a PR for this, and a runtime [workaround](https://github.com/bigskysoftware/_hyperscript/pull/567#issuecomment-2364256479)
