### ISSUE TITLE
Minifier for Hyperscript

### ISSUE THREAD

**Issue by fullnitrous** [bigskysoftware/_hyperscript#566]
Is there any consideration to create a hyperscript minifier such that
```html
<div_="
    on click
        toggle .test
"></div>
```
minifies to
```html
<div_="on click toggle .test"></div>
```
also for
```html
<script type="text/hyperscript"></script>
```
blocks and also for .hs files.

Would be good for the maturity of the language / for production use.

**Comment by 1cg** [comment]
new lines has a meaning in at least one case `else if` on the same line will be interpreted as the if binding to the else, if there is a newline the if will be within the else

minification is also kinda against the spirit of hyperscript, which is readability in place over pretty much everything (including perf)
