### ISSUE TITLE
hs and data-hs attributes not working?

### ISSUE THREAD

**Issue by nikalexis** [bigskysoftware/_hyperscript#585]
From the `README.md`:

```
<script src="https://unpkg.com/hyperscript.org@0.9.13"></script>


<button _="on click toggle .clicked">
  Toggle the "clicked" class on me
</button>


<div hs="on mouseOver toggle mouse-over on #foo">
</div>

<div data-hs="on click call aJavascriptFunction() then
              wait 10s then
              call anotherJavascriptFunction()">
           Do some stuff
</div>
```

I tried `hs` and `data-hs` attributes, but are not working for me.

In contrary, [copied from the docs](https://hyperscript.org/docs/#install).
> It's worth mentioning that, if you prefer, you can use script or data-script instead of _ when using hyperscript:

`script` and `data-script` are working fine.

**Comment by 1cg** [comment]
yikes that's been wrong for a while!
