### ISSUE TITLE
Parent ‘on load’ event triggering multiple times due to DOM re-renders or updates with child event handlers

### ISSUE THREAD

**Issue by restless** [bigskysoftware/_hyperscript#586]
I'm not 100% sure if that's a bug but I believe is either unexpected or expected but not documented.

Simply put, when the page defined below is opened then the "on load" event is triggered 3 times. At the same time the "init" is executed only once (as expected). It can be validated in the devtools by checking the printed messages.

```
<html>
  <head>
    <script src="https://unpkg.com/hyperscript.org@0.9.13"></script>
  </head>
  <body>

    <div _="on load log 'on load'">
      On load
      <button _="on click log 'clicked'">Click me</button>
      <button _="on click log 'clicked 2'">Click me too</button>
    </div>

    <div _="init log 'init'">
      Init
      <button _="on click log 'clicked'">Click me</button>
    </div>

  </body>
</html>
```

So, is it expected or it's a bug?

**Comment by 1cg** [comment]
yes, expected, the `load` event bubbles:

https://github.com/bigskysoftware/_hyperscript/blob/e8752794640266eb16d4cfeac9bda988e5e0eb8c/src/_hyperscript.js#L2004
