### ISSUE TITLE
catch does not work with fetch statement with if

### ISSUE THREAD

**Issue by shaozi** [bigskysoftware/_hyperscript#588]
The `if` in `fetch` caused the `catch` not working.

### Setup
client: 

```html
 <button
            class="btn"
            _="
               on click fetch /api/toggle/1
                        if it is 'on' then add .on to me else remove .on from me end
                        catch e log e
                        "
          >
           Toggle
          </button>

```
server: returnss a 404 page not found error.

### Result

However, the `catch e log e` is never triggered.

## What is working

But if I replace the `if` with a `log`, it works.

```html
 <button
            class="btn"
            _="
               on click fetch /api/toggle/1
                        log it
                        catch e log e
                        "
          >
          Toggle
          </button>
```

**Comment by 1cg** [comment]
believe it or not `fetch()` doesn't throw on a 404:

https://stackoverflow.com/questions/38235715/fetch-reject-promise-and-catch-the-error-if-status-is-not-ok

so what's happening here is that no exception is happening.  In the second example it's the `log it` that is printing the response.

**Comment by shaozi** [comment]
aha! 
So in fetch how to check the return code?
