### ISSUE TITLE
How to add data-* attribute?

### ISSUE THREAD

**Issue by gmzu** [bigskysoftware/_hyperscript#60]
How can an attribute of the type data-* be added to an element?
If I use
`on click add [data-initial='name']`
I get this error
`Expected ']' but found 'data-initial'`

**Comment by 1cg** [comment]
I have just fixed this issue in `dev`.  Are you willing to test against a dev release?

**Comment by gmzu** [comment]
Yes, I'm trying to develop a whole web app using client side almost exclusively htmx and hyperscript.
If I win the challenge, I'll spread your "verb"😉

**Comment by 1cg** [comment]
Ha! I just generated a new version of the 0.0.6 release, you can grab it here:

https://raw.githubusercontent.com/bigskysoftware/_hyperscript/dev/dist/_hyperscript.js

Cheers!
Carson

/// big sky software ///

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gmzu** [comment]
With new version this command works
`on click add [data-initial='name']`
but Is there a way to pass a variable value instead of static value 'name'??

**Comment by 1cg** [comment]
Ah, got it.  OK property literals are static now, no dynamic values (they conflict w/ array literals in the grammar, so it's tough to make them general expressions)

I may be able to fix that at some point, but not right now.  This will work however in the latest version w/ pseudoCommands:

```on click setAttribute('data-initial', myExpression() )```

**Comment by gmzu** [comment]
works like a charm!! great job!!

**Comment by 1cg** [comment]
great!
