### ISSUE TITLE
on load event on <img> is triggered twice

### ISSUE THREAD

**Issue by gmzu** [bigskysoftware/_hyperscript#65]
This code 

`<img  src="image-url" _="on load log me.src" >`

create two console log entry with same "image-url"

I suppose because is intercepted "load" node event and "load" image specific event.
Is there any way to distinguish the two events?

In addition if I use
` <img src="" onload="myFunction(this)">`
and programmatically I set src to image-url, myFunction is correctly executed after remote image-url is loaded

if I use
`<img src="" onload="myFunction(this)"_="on click log me">`
and I don't set src programmatically, myFunction is always executed on page load

**Comment by 1cg** [comment]
In the 0.0.6 release (this week) we are going to support init blocks:

https://dev.hyperscript.org/features/init/

That should address this use case.  Reasonable?

**Comment by gmzu** [comment]
> In the 0.0.6 release (this week) we are going to support init blocks:
> 
> https://dev.hyperscript.org/features/init/
> 
> That should address this use case. Reasonable?

Thank you for your answer!
It depends on how the load event is handled.
The problem that occurred is that the specific load event of an img element (which is triggered at the end of its src loading) is triggered even when the node is loaded.
The help reports "the init keyword allows you to run some hyperscript immediately when an element initializes", but if the load event trigger also load src event, the latter cannot be handled.
I solved it using javascript onload in img element, without using hyperscript on img element, because, as I said in my previous post, if I use hyperscript as an attribute of an img element also js onload is executed twice

**Comment by 1cg** [comment]
OK, here is my solution: we include a `hyperscript:true` in the detail for the event we fire.  So you should be able to write this:

```html
<img src="image-url" _="on load[not detail.hyperscript] log me.src" >
<img src="image-url" _="on load[detail.hyperscript is not true] log me.src" >
```

Does that work as a solution?

**Comment by gmzu** [comment]
Theoretically yes, but I don't see a hyperscript property in event.detail (or is it a feature that needs to be implemented?)
In this specific case (img element) I discovered that I could also use
```html
<img src="image-url" _="on load[not detail] log me.src" >
```
since load image source event does not have a detail

**Comment by 1cg** [comment]
Are you using the latest version of hyperscript (released today :) 0.0.6?

Yes, checking for the presence of a detail object would work.  You could shorten it to:

```html
<img src="image-url" _="on load[no detail] log me.src" >
```

`no` is a null check  :)

**Comment by gmzu** [comment]
I was still using the dev version!! It works perfectly! Thanks!

**Comment by 1cg** [comment]
awesome, thank you for being brave enough to use hyperscript! :)
