### ISSUE TITLE
Extracting part of HTML or JSON response from AJAX

### ISSUE THREAD

**Issue by marad** [bigskysoftware/_hyperscript#7]
Hi, is it possible to extract some part of the response from `ajax` command?

For now I'd need to do something like this:

```
on click ajax GET /my-data then put response(#content) before me end
```

This is of course just to give you an idea of what I would use. Important thing here to remember is that the response could be json or any other format, so the language should address that somehow.

Alternatively it could just be left to custom JS function that would extract the value.

**Comment by chg20** [comment]
interesting use case!

right now the response object is just a string, so you would need to write a `select()` function in javascript:

```
  on click ajax GET /my-data then put select(#content, response) before me
```

The id literal will evaluate to the string "#content" to invoke the javascript function with.

`select` does feel like it should be built into the language though!

**Comment by chg20** [comment]
```
  select <css selector> [from <expr>]
```

where a css selector is any valid selecto

if no `from` clause, select against the document

if from clause and DOM element, select against it

if from clause and String, convert to DOM and select against it

that would be a great feature!

```
on click ajax GET /my-data then put select #content from response before me
```

**Comment by chg20** [comment]
I might write it as:

```
on click ajax GET /my-data then 
             set content to select #content from response then 
             put content before me
```

for clarity

**Comment by marad** [comment]
Your proposal looks great and would totally address my needs! Please implement it! 👍 

How about JSON though? Is that something that could be useful?

**Comment by chg20** [comment]
I think JSON is a separate thing.  If people want to use the CSS selection syntax against it they can transform it into either an html string or a DOM with whatever client side template tool they are using:

```
on click ajax GET /my-data then 
             set html to Mustache.render("#someTemplate", JSON.parse(response))
             set content to select #content from html then 
             put content before me
```

As much as I'd like to dive into this now, I am extremely busy for the next month and will not likely get to it until August.  Sorry about that.

**Comment by marad** [comment]
No need to be sorry @chg20. Your work here is awesome and I'm greatful for what you already delivered. Keep up the good work! 😃

**Comment by marad** [comment]
As for the JSON - I was thinking about extracting a field from json to use in the script as a value, but maybe that's already supported.

**Comment by benpate** [comment]
Howdy @marad --

In case you haven't already found the answer to this, you can decode JSON values by adding `as json` to the variable.  So, if your server is sending back a JSON dataset, you could use this to get at the data:

```hyperscript
fetch /people/1 as json
log it
put it.firstName into #firstName
put it.lastName into #lastName
--- etc..
```

Here are the [other conversions](https://hyperscript.org/expressions/as/) hyperscript can do.  Does this work for you?

**Comment by marad** [comment]
@benpate It sure does for JSON. Could you also provide (if possible) an example of how could I use it to extract part of the HTML that server sent?

**Comment by benpate** [comment]
Hi @marad - I think you're looking for something that would parse and query the HTML, but please let me know if I'm going down the wrong path.

Hyperscript does not have a specific `as` conversion for this (yet) but you should be able to do something using the browser itself.  For instance, if your server returns HTML, just drop it into the DOM somewhere and then query it normally.  If you don't want your users seeing it, you could 1) just put it somewhere hidden, or 2) make an artificial DOM node that's not a part of the document.

Here's a really rough example that should get you pointed in the right direction:

```html
<div id="hiddenElement" style="display:none;"></div>

<script type="text/hyperscript">
fetch /foo
put it into #hiddenElement
repeat in <#hiddenElement .selectorClass />
    log it
end
</script>
```

Does this work for you?  If you'd like to go more in depth, I'm happy to [chat privately on Discord](htmx & hyperscript discord server)

**Comment by marad** [comment]
@benpate Thanks for the code. I'm not working on the project right now, but I needed a way to get the only the part of the HTML response into some element. So going along the lines of your solution I would have to put it into hidden element, and then basically copy the interesting part.

Problem here is that the response from the server was the whole HTML (with html, head and body tags) - I'm not sure if this approach would work (maybe with artificial DOM element it would?).

Anyway - right now I don't work on the project and I can't really check if this is what I need - I just wanted to get some more information for other people that would land here (and probably for myself in the future). 

Thanks for your responses. I think I'm ready to close this now ;)
