### ISSUE TITLE
Can't call functions with _ or empty parameter lists

### ISSUE THREAD

**Issue by boxed** [bigskysoftware/_hyperscript#8]
Tried to do `on load call auto_select()`. This crashes with a vague message about `_`. If I rename the function to `autoSelect` it crashes if I call it with zero parameters like that. 

Still haven't gotten it to work with those two changes though...

**Comment by julianebeli** [comment]
I've found that you can't use '_' in a function or attribute name.
Functions with no parameters don't see to get called at all.
Instead of 'a_function()' i use 'aFunction(1)'

**Comment by 1cg** [comment]
This is fixed in dev, sorry for the very rough alpha state of the project!
