### ISSUE TITLE
FEATURE: “is empty” and “is not empty”

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#82]
I was recently working with a string comparison and I struggled to guarantee that an object was not `null`.  While I eventually worked it out as `not(no value)` I think we could make hyperscript more readable with another pair of single argument operators: `is empty` and `is not empty`.

My first thought is that `is empty` should return `true`for all values that are `null`, `undefined`, [empty string], or zero length Objects or ArrayLike values.  But if someone else has a better definition, I'm open to whatever makes the most sense for the community.  The `is not empty` operator would obviously return the opposite of `is empty`.  

I'll happily take a shot at building this (along with tests and documentation) if I can get a hoo-ah from @1cg

**Comment by 1cg** [comment]
hoo-ah
