### ISSUE TITLE
Documentation anchors partially broken.

### ISSUE THREAD

**Issue by apollo13** [bigskysoftware/_hyperscript#87]
* Navigating to https://hyperscript.org/docs/ and clicking on "worker" yields the anchor `#worker`, should probably be `#workers`.
 * https://hyperscript.org/docs/#js says "The js feature allows" and links to the worker feature, " inline javascript " in the last sentence links to nothing (or at least I do not know where it is supposed to link to :D)

**Comment by 1cg** [comment]
fixed, thank you!
