### ISSUE TITLE
Trouble with "measure" command

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/_hyperscript#90]
I love the new measure command, but I'm running into trouble using it.  Here's my code:

```
def center(node) 
	with node measure me then log it end -- works
	measure node then log it -- doesn't work.
end
```

I want to make a function that takes an HTML Element and moves it around the screen.  The first statement `with node...` works fine, and I'm able to get the measurement of the Element.  But the second statement returns an error "Uncaught (in promise) No such measurement as node". I think this is because it does not recognize the variable as a node, and assumes that it is a (missing) dimension that it's supposed to find.

So, perhaps we need to update the syntax that `measure` is using?

Also, being able to pull specific measurements into variables is nice, but it's no use if I have to measure two items (like the window and the HTML Element I'm going to move).  The best I've come up with is the rather clunky 

```
measure #sourceNode then put it into sourceMeasurement
measure #targetNode then put it into targetMeasurement

... then use the two new variables below
```

How much flexibility do we have to tweak this command?

**Comment by dz4k** [comment]
This is a tough one... It'll be hard to support both implicit `me` and using variables as targets. Consider this code:

```hyperscript
set top to the first <li/> in me
measure top -- measure the ul's "top", or measure everything about the li?
```

As a workaround for your issue, you can use `the` `element` or `elements` to disambiguate:

```hyperscript
measure the node
measure element node
```

**Comment by benpate** [comment]
Thanks Deniz.  I think this will work great.
