### ISSUE TITLE
How do I access attribute values?

### ISSUE THREAD

**Issue by zilti** [bigskysoftware/_hyperscript#95]
I noticed this gives me `undefined`:

`log #element[attr-name]`

as does `log #element.attr-name` and `log attr-name of #element`. What is the correct way to read an attribute value?

**Comment by 1cg** [comment]
We are still finalizing the attribute syntax.  The css standard, [attribute name] conflicts with array access and array literals.

For right now, you can write this:

```
log #element's attribute <attr-name>
```

But this may not be our final answer.  Sorry about that!

**Comment by zilti** [comment]
That does not work, it will complain about an unclosed string (at least that happened with the example on https://hyperscript.org/expressions/possessive/). For now I am using an embedded javascript.
